# Generated by Django 4.2.26 on 2025-11-26 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSupportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст ответа')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='Категория')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Использований')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Быстрый ответ',
                'verbose_name_plural': 'Быстрые ответы',
                'ordering': ['-usage_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Имя')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('waiting_user', 'Ожидает ответа пользователя'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('category', models.CharField(blank=True, default='', help_text='Техническая проблема, Вопрос по функционалу и т.д.', max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('page_url', models.TextField(blank=True, default='', verbose_name='URL страницы')),
                ('screenshot', models.TextField(blank=True, default='', verbose_name='Скриншот (base64)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('user', models.ForeignKey(blank=True, help_text='Может быть пустым для анонимных обращений', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff_reply', models.BooleanField(default=False, verbose_name='Ответ от поддержки')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('attachments', models.TextField(blank=True, default='', help_text='JSON список ссылок на файлы', verbose_name='Вложения (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('read_by_user', models.BooleanField(default=False, verbose_name='Прочитано пользователем')),
                ('read_by_staff', models.BooleanField(default=False, verbose_name='Прочитано поддержкой')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки',
                'ordering': ['created_at'],
            },
        ),
    ]
