# Generated by Django 5.2.8 on 2026-01-21 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='actual_behavior',
            field=models.TextField(blank=True, default='', verbose_name='Фактическое поведение'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='browser_info',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Браузер'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='build_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Версия билда'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='expected_behavior',
            field=models.TextField(blank=True, default='', verbose_name='Ожидаемое поведение'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый ответ'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='screen_resolution',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, default='', verbose_name='Шаги воспроизведения'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Статус подписки'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_role',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('login', 'Вход/Регистрация'), ('payment', 'Оплата/Подписка'), ('lesson', 'Уроки/Расписание'), ('zoom', 'Zoom/Видеосвязь'), ('homework', 'Домашние задания'), ('recording', 'Записи уроков'), ('other', 'Другое')], default='other', help_text='Категория проблемы для быстрого триажа', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('p0', 'P0 - Инцидент (всем плохо)'), ('p1', 'P1 - Критично (блокирует работу)'), ('p2', 'P2 - Важно (есть обходной путь)'), ('p3', 'P3 - Низкий (вопрос/пожелание)')], default='p2', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('operational', 'Всё работает'), ('degraded', 'Частичные проблемы'), ('major_outage', 'Серьёзный сбой'), ('maintenance', 'Техобслуживание')], default='operational', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, default='', help_text='Публичное сообщение о статусе', verbose_name='Сообщение')),
                ('incident_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Название инцидента')),
                ('incident_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало инцидента')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Статус системы',
                'verbose_name_plural': 'Статус системы',
            },
        ),
    ]
