# Generated by Django 5.2.8 on 2026-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_system_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('web', 'Веб-форма'), ('telegram', 'Telegram'), ('email', 'Email'), ('admin', 'Создано админом')], default='web', max_length=20, verbose_name='Источник'),
        ),
    ]
