# Generated by Django 5.2.8 on 2026-03-04 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_add_source_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME-тип')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('local_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь на диске')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='support.supportmessage', verbose_name='Сообщение')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportticket', verbose_name='Тикет')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение поддержки',
                'verbose_name_plural': 'Вложения поддержки',
                'ordering': ['created_at'],
            },
        ),
    ]
