# Generated by Django 5.2.8 on 2026-02-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_add_source_field'),
        ('tenants', '0002_create_default_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа отправителя тикета', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenants.school'),
        ),
    ]
