# Generated by Django 5.2.11 on 2026-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_tenant'),
        ('support', '0004_add_school_fk_to_ticket'),
    ]

    operations = [
    ]
