# Generated by Django 5.2.8 on 2025-11-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.DeleteModel(name='Assignment'),
        migrations.DeleteModel(name='Lesson'),
        migrations.DeleteModel(name='Submission'),
    ]
