# Generated by Django 4.2.26 on 2025-11-26 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_remove_submission_assignment_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('grade', 'Выставление оценки'), ('submit', 'Отправка работы'), ('view', 'Просмотр'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('other', 'Другое')], db_index=True, help_text='Тип действия', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Описание действия')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес пользователя', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent браузера')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Время действия')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, совершивший действие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудит-лог',
                'verbose_name_plural': 'Аудит-логи',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action', '-timestamp'], name='audit_user_action_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_content_idx'), models.Index(fields=['-timestamp'], name='audit_timestamp_idx')],
            },
        ),
    ]
