# Generated by Django 4.2 on 2026-02-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0009_group_invite_code'),
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('yandex_embed_url', models.URLField(max_length=1024, verbose_name='URL для iframe (Яндекс Диск)')),
                ('yandex_public_url', models.URLField(blank=True, max_length=1024, verbose_name='Публичная ссылка (опционально)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('watermark_enabled', models.BooleanField(default=True, verbose_name='Водяной знак включен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protected_contents', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protected_contents', to='schedule.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Защищённый контент',
                'verbose_name_plural': 'Защищённый контент',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('blocked', 'Заблокирована'), ('ended', 'Завершена'), ('expired', 'Истекла')], db_index=True, default='active', max_length=20)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='core.protectedcontent', verbose_name='Контент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_access_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия доступа к контенту',
                'verbose_name_plural': 'Сессии доступа к контенту',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status', '-started_at'], name='content_session_user_idx'), models.Index(fields=['content', 'status'], name='content_session_content_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_hidden', 'Tab hidden'), ('window_blur', 'Window blur'), ('fullscreen_exited', 'Fullscreen exited'), ('print_screen_pressed', 'Print screen pressed'), ('devtools_opened', 'Devtools opened'), ('screen_recording_suspected', 'Screen recording suspected'), ('display_capture_detected', 'Display capture detected'), ('multiple_screens_detected', 'Multiple screens detected'), ('watermark_tamper_detected', 'Watermark tamper detected'), ('network_proxy_detected', 'Network proxy detected'), ('heartbeat_anomaly', 'Heartbeat anomaly')], db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('score_delta', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='core.contentaccesssession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Событие безопасности контента',
                'verbose_name_plural': 'События безопасности контента',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', '-created_at'], name='content_event_session_idx'), models.Index(fields=['event_type', '-created_at'], name='content_event_type_idx')],
            },
        ),
    ]
