# Generated by Django 5.2.11 on 2026-02-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_protectedcontent_contentaccesssession_and_more'),
        ('tenants', '0004_school_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_audit_logs_tenant', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AddField(
            model_name='contentaccesssession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_access_sessions', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AddField(
            model_name='protectedcontent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protected_contents', to='tenants.tenant', verbose_name='Тенант'),
        ),
    ]
