# Generated by Django 5.2.11 on 2026-02-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_status_courselesson_homework_coursemodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedcontent',
            name='lesson',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='protected_content',
                to='core.courselesson',
                verbose_name='Урок курса',
            ),
        ),
    ]
