# Generated by Django 5.2.11 on 2026-02-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_protectedcontent_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='kinescope_embed_url',
            field=models.URLField(blank=True, help_text='Embed-ссылка для плеера Kinescope', max_length=1024, verbose_name='Kinescope Embed URL'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='kinescope_video_id',
            field=models.CharField(blank=True, help_text='ID видео в Kinescope (заполняется автоматически)', max_length=255, verbose_name='Kinescope Video ID'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='video_provider',
            field=models.CharField(choices=[('local', 'Локальное хранилище'), ('kinescope', 'Kinescope'), ('external', 'Внешняя ссылка')], default='local', max_length=20, verbose_name='Провайдер видео'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='video_status',
            field=models.CharField(choices=[('none', 'Нет видео'), ('uploading', 'Загружается'), ('processing', 'Обрабатывается'), ('ready', 'Готово'), ('error', 'Ошибка')], default='none', max_length=20, verbose_name='Статус видео'),
        ),
    ]
