# Generated by Django 5.2.8 on 2025-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель'), ('admin', 'Администратор')], help_text='Ученик, Учитель или Администратор', max_length=20, verbose_name='роль'),
        ),
    ]
