# Generated by Django 5.2.8 on 2025-11-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zoom_account_id',
            field=models.CharField(blank=True, default='', help_text='Account ID для Zoom API (только для учителей)', max_length=255, verbose_name='Zoom Account ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zoom_client_id',
            field=models.CharField(blank=True, default='', help_text='Client ID для Zoom API (только для учителей)', max_length=255, verbose_name='Zoom Client ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zoom_client_secret',
            field=models.CharField(blank=True, default='', help_text='Client Secret для Zoom API (только для учителей)', max_length=255, verbose_name='Zoom Client Secret'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zoom_user_id',
            field=models.CharField(blank=True, default='', help_text='User ID в Zoom (обычно email или ID пользователя)', max_length=255, verbose_name='Zoom User ID'),
        ),
    ]
