# Generated by Django 5.2.8 on 2025-11-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_zoom_account_id_customuser_zoom_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBarMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('target', models.CharField(choices=[('teachers', 'Учителя'), ('students', 'Ученики'), ('all', 'Все')], max_length=20, verbose_name='Для кого')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение статус-бара',
                'verbose_name_plural': 'Сообщения статус-бара',
                'ordering': ['-created_at'],
            },
        ),
    ]
