# Generated by Django 5.2.8 on 2025-11-17 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phoneverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен верификации')),
                ('code', models.CharField(max_length=6, verbose_name='Код верификации')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('attempts', models.IntegerField(default=0, verbose_name='Попыток проверки')),
            ],
            options={
                'verbose_name': 'Верификация email',
                'verbose_name_plural': 'Верификации email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email верифицирован'),
        ),
    ]
