# Generated by Django 5.2.8 on 2025-11-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailverification_customuser_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(default='noreply@teachingpanel.com', help_text='Email, от имени которого отправляются письма', max_length=254, verbose_name='Email отправителя')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Email уведомления включены')),
                ('welcome_email_enabled', models.BooleanField(default=True, help_text='Отправлять письмо при регистрации', verbose_name='Приветственное письмо')),
                ('lesson_reminder_hours', models.IntegerField(default=2, help_text='За сколько часов напоминать о занятии', verbose_name='Напоминание о занятии (часов)')),
                ('homework_deadline_reminder_hours', models.IntegerField(default=24, help_text='За сколько часов напоминать о дедлайне', verbose_name='Напоминание о дедлайне ДЗ (часов)')),
                ('push_notifications_enabled', models.BooleanField(default=False, verbose_name='Push уведомления')),
                ('default_lesson_duration', models.IntegerField(default=60, help_text='Длительность занятия по умолчанию', verbose_name='Длительность занятия (минут)')),
                ('auto_recording', models.BooleanField(default=False, help_text='Автоматически записывать занятия', verbose_name='Автозапись занятий')),
                ('waiting_room_enabled', models.BooleanField(default=True, help_text='Включить комнату ожидания в Zoom', verbose_name='Комната ожидания')),
                ('min_booking_hours', models.IntegerField(default=2, help_text='За сколько часов минимум можно забронировать занятие', verbose_name='Минимум часов до занятия')),
                ('max_booking_days', models.IntegerField(default=30, help_text='На сколько дней вперед можно бронировать', verbose_name='Максимум дней вперед')),
                ('cancellation_hours', models.IntegerField(default=24, help_text='За сколько часов можно отменить занятие', verbose_name='Отмена занятия (часов)')),
                ('platform_name', models.CharField(default='Teaching Panel', help_text='Название, отображаемое в интерфейсе', max_length=100, verbose_name='Название платформы')),
                ('support_email', models.EmailField(default='support@teachingpanel.com', max_length=254, verbose_name='Email поддержки')),
                ('logo_url', models.URLField(blank=True, default='', help_text='Ссылка на логотип платформы', verbose_name='URL логотипа')),
                ('primary_color', models.CharField(default='#4F46E5', help_text='HEX код основного цвета интерфейса', max_length=7, verbose_name='Основной цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
