# Generated by Django 4.2.26 on 2025-11-26 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID пользователя в Telegram для восстановления пароля и уведомлений', max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, default='', help_text='Username в Telegram (опционально)', max_length=50, verbose_name='Telegram Username'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Уникальный токен для восстановления пароля', max_length=64, unique=True, verbose_name='токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('expires_at', models.DateTimeField(verbose_name='истекает')),
                ('used', models.BooleanField(default=False, verbose_name='использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='использован в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'токен восстановления пароля',
                'verbose_name_plural': 'токены восстановления пароля',
                'ordering': ['-created_at'],
            },
        ),
    ]
