# Generated by Django 4.2.26 on 2025-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_telegram_id_customuser_telegram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID для отправки сообщений через бота', max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
