# Generated by Django 5.2.11 on 2026-02-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_telegram_chat_id'),
        ('tenants', '0004_school_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AddField(
            model_name='statusbarmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_bar_messages', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='tenants.tenant', verbose_name='Тенант'),
        ),
    ]
