# Generated by Django 4.2.26 on 2025-11-30 21:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='base_storage_gb',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extra_storage_gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='used_storage_gb',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
