# Generated by Django 4.2.26 on 2025-12-01 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_notification_settings(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    NotificationSettings = apps.get_model('accounts', 'NotificationSettings')
    for user in User.objects.all().iterator():
        NotificationSettings.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subscription_base_storage_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_verified',
            field=models.BooleanField(default=False, help_text='Флаг показывает, что пользователь подтвердил привязку Telegram через бота', verbose_name='Telegram подтверждён'),
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'код привязки Telegram',
                'verbose_name_plural': 'коды привязки Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_enabled', models.BooleanField(default=True)),
                ('notify_homework_submitted', models.BooleanField(default=True)),
                ('notify_subscription_expiring', models.BooleanField(default=True)),
                ('notify_payment_success', models.BooleanField(default=True)),
                ('notify_homework_graded', models.BooleanField(default=True)),
                ('notify_homework_deadline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'настройки уведомлений',
                'verbose_name_plural': 'настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('homework_submitted', 'ДЗ сдано учеником'), ('homework_graded', 'ДЗ проверено учителем'), ('homework_deadline', 'Напоминание о дедлайне ДЗ'), ('subscription_expiring', 'Истекает подписка'), ('payment_success', 'Оплата прошла успешно')], max_length=64)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('skipped', 'Пропущено'), ('failed', 'Ошибка')], default='sent', max_length=20)),
                ('message', models.TextField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'лог уведомлений',
                'verbose_name_plural': 'логи уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_notification_settings, migrations.RunPython.noop),
    ]
