# Generated by Django 4.2.26 on 2025-12-01 13:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_telegram_verified_telegramlinkcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_lesson_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_new_homework',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('homework_submitted', 'ДЗ сдано учеником'),
                    ('homework_graded', 'ДЗ проверено учителем'),
                    ('homework_deadline', 'Напоминание о дедлайне ДЗ'),
                    ('subscription_expiring', 'Истекает подписка'),
                    ('payment_success', 'Оплата прошла успешно'),
                    ('lesson_reminder', 'Напоминание об уроке'),
                    ('new_homework', 'Новое домашнее задание'),
                ],
                max_length=64,
            ),
        ),
    ]
