# Generated by Django 4.2.26 on 2025-12-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_lessonrecording_allowed_groups_and_more'),
        ('accounts', '0015_extend_notification_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualStudent',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='individual_student_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
                ('teacher_notes', models.TextField(blank=True, default='', help_text='Заметки преподавателя об ученике', verbose_name='замечания учителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_students', to=settings.AUTH_USER_MODEL, verbose_name='основной учитель')),
            ],
            options={
                'verbose_name': 'индивидуальный ученик',
                'verbose_name_plural': 'индивидуальные ученики',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, help_text='Сумма всех очков (посещение + ДЗ + контроль)', verbose_name='общие очки')),
                ('attendance_points', models.IntegerField(default=0, help_text='Очки за посещения занятий', verbose_name='очки за посещение')),
                ('homework_points', models.IntegerField(default=0, help_text='Очки за выполненные домашние задания', verbose_name='очки за ДЗ')),
                ('control_points_value', models.IntegerField(db_column='control_points', default=0, help_text='Очки за пройденные контрольные точки', verbose_name='очки за контрольные точки')),
                ('rank', models.IntegerField(default=0, help_text='Место в рейтинге группы (0 если нет группы)', verbose_name='место в рейтинге')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='schedule.group', verbose_name='группа')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'рейтинг ученика',
                'verbose_name_plural': 'рейтинги учеников',
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['group', '-total_points'], name='accounts_us_group_i_10b03f_idx'), models.Index(fields=['user', 'group'], name='accounts_us_user_id_a71d10_idx')],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('attended', '✅ Был'), ('absent', '❌ Не был'), ('watched_recording', '👁️ Посмотрел запись')], max_length=20, null=True, verbose_name='статус посещения')),
                ('auto_recorded', models.BooleanField(default=False, help_text='True если заполнено при подключении к Zoom', verbose_name='автоматически заполнено')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schedule.lesson', verbose_name='занятие')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='заполнил (учитель)')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'запись посещения',
                'verbose_name_plural': 'записи посещения',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['lesson', 'student'], name='accounts_at_lesson__d5ca80_idx'), models.Index(fields=['student', '-recorded_at'], name='accounts_at_student_c60e9d_idx'), models.Index(fields=['status', 'recorded_at'], name='accounts_at_status_ffa456_idx')],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
