# Generated by Django 4.2.26 on 2025-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_individualstudent_userrating_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, default='', help_text='ID главной папки учителя в Google Drive (только для учителей)', max_length=255, verbose_name='Google Drive Folder ID'),
        ),
    ]
