# Generated by Django 5.2.8 on 2025-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_gdrive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='base_storage_gb',
            field=models.IntegerField(default=15),
        ),
    ]
