# Generated by Django 5.2.8 on 2025-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_gdrive_folder_to_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='base_storage_gb',
            field=models.IntegerField(default=10),
        ),
    ]
