# Generated by Django 5.2.8 on 2025-12-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_update_existing_subscriptions_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zoom_pmi_link',
            field=models.URLField(blank=True, default='', help_text='Постоянная ссылка Zoom (Personal Meeting ID) для регулярных уроков', max_length=500, verbose_name='Zoom PMI ссылка'),
        ),
    ]
