# Generated by Django 5.2.8 on 2025-12-26 11:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import string
import random


def generate_referral_codes(apps, schema_editor):
    """Генерирует уникальные referral_code для всех существующих пользователей."""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    chars = string.ascii_uppercase + string.digits
    
    existing_codes = set()
    for user in CustomUser.objects.all():
        if user.referral_code:
            existing_codes.add(user.referral_code)
    
    for user in CustomUser.objects.filter(referral_code=''):
        while True:
            code = ''.join(random.choices(chars, k=8))
            if code not in existing_codes:
                existing_codes.add(code)
                user.referral_code = code
                user.save(update_fields=['referral_code'])
                break


def reverse_referral_codes(apps, schema_editor):
    """Обратная миграция - ничего не делаем."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_telegram_notifications'),
    ]

    operations = [
        # Шаг 1: Добавляем поле БЕЗ unique
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, default='', help_text='Уникальный код для реферальной ссылки (например: ?ref=CODE)', max_length=12, verbose_name='реферальный код'),
        ),
        
        # Шаг 2: Генерируем уникальные коды для существующих пользователей
        migrations.RunPython(generate_referral_codes, reverse_referral_codes),
        
        # Шаг 3: Теперь добавляем unique constraint
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, default='', help_text='Уникальный код для реферальной ссылки (например: ?ref=CODE)', max_length=12, unique=True, verbose_name='реферальный код'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Пригласивший пользователь (если пришёл по реферальной ссылке)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, default='', max_length=32)),
                ('utm_source', models.CharField(blank=True, default='', max_length=64)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=64)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=64)),
                ('channel', models.CharField(blank=True, default='', help_text='Канал (например, Telegram/GroupName)', max_length=64)),
                ('ref_url', models.URLField(blank=True, default='')),
                ('cookie_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_attributions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'атрибуция реферала',
                'verbose_name_plural': 'атрибуции рефералов',
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код для URL (?ref=CODE)', max_length=32, unique=True, verbose_name='код ссылки')),
                ('name', models.CharField(help_text='Название для идентификации (например, "ТГ канал @example")', max_length=128, verbose_name='название')),
                ('partner_name', models.CharField(blank=True, default='', help_text='Имя/контакт человека, который рекламирует', max_length=128, verbose_name='имя партнёра')),
                ('partner_contact', models.CharField(blank=True, default='', help_text='Telegram/email/телефон партнёра для выплат', max_length=255, verbose_name='контакт партнёра')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('750.00'), help_text='Сумма выплаты партнёру за каждую оплату', max_digits=10, verbose_name='комиссия за оплату')),
                ('utm_source', models.CharField(blank=True, default='telegram', max_length=64)),
                ('utm_medium', models.CharField(blank=True, default='referral', max_length=64)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=64)),
                ('clicks_count', models.IntegerField(default=0, verbose_name='кликов')),
                ('registrations_count', models.IntegerField(default=0, verbose_name='регистраций')),
                ('payments_count', models.IntegerField(default=0, verbose_name='оплат')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='всего заработано партнёром')),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='выплачено партнёру')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('notes', models.TextField(blank=True, default='', verbose_name='заметки')),
            ],
            options={
                'verbose_name': 'реферальная ссылка',
                'verbose_name_plural': 'реферальные ссылки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_re_code_04813f_idx'), models.Index(fields=['is_active', '-created_at'], name='accounts_re_is_acti_ae6574_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает выплаты'), ('paid', 'Выплачено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission', to='accounts.payment')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'реферальная комиссия',
                'verbose_name_plural': 'реферальные комиссии',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', 'status'], name='accounts_re_referre_84f077_idx'), models.Index(fields=['referred_user'], name='accounts_re_referre_82ae5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, default='', verbose_name='Referer')),
                ('cookie_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время клика')),
                ('resulted_in_registration', models.BooleanField(default=False, verbose_name='привёл к регистрации')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_clicks', to=settings.AUTH_USER_MODEL, verbose_name='зарегистрированный пользователь')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='accounts.referrallink', verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'клик по реферальной ссылке',
                'verbose_name_plural': 'клики по реферальным ссылкам',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['link', '-created_at'], name='accounts_re_link_id_ebe249_idx'), models.Index(fields=['cookie_id'], name='accounts_re_cookie__2a22d6_idx')],
            },
        ),
    ]
