# Generated by Django 5.2.8 on 2025-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_referral_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralattribution',
            name='ref_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
