# Generated by Django 5.2.8 on 2026-01-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_chat_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='absence_alert_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='Минимальное количество пропусков подряд для уведомления (0 = отключено)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='grading_backlog_hours',
            field=models.PositiveSmallIntegerField(default=48, help_text='Сколько часов работа может висеть без проверки'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='grading_backlog_threshold',
            field=models.PositiveSmallIntegerField(default=5, help_text='Минимальное количество непроверенных работ для уведомления'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='inactive_student_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Количество дней без активности для уведомления'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_absence_alert',
            field=models.BooleanField(default=True, help_text='Уведомления о сериях пропусков учеников'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_achievement',
            field=models.BooleanField(default=False, help_text='Уведомления о достижениях и прогрессе'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_control_point_deadline',
            field=models.BooleanField(default=True, help_text='Напоминания о контрольных точках'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_grading_backlog',
            field=models.BooleanField(default=True, help_text='Уведомления о накопившихся непроверенных ДЗ'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_group_health',
            field=models.BooleanField(default=True, help_text='Уведомления об аномалиях по группе (посещаемость/успеваемость)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_inactive_student',
            field=models.BooleanField(default=True, help_text='Уведомления о неактивных учениках'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_inactivity_nudge',
            field=models.BooleanField(default=True, help_text='Мягкие напоминания при длительном отсутствии активности'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_performance_drop',
            field=models.BooleanField(default=True, help_text='Уведомления о падении успеваемости ученика'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_student_absence_warning',
            field=models.BooleanField(default=True, help_text='Предупреждения ученику о его пропусках'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='performance_drop_percent',
            field=models.PositiveSmallIntegerField(default=20, help_text='Процент падения среднего балла для уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('homework_submitted', 'ДЗ сдано учеником'), ('homework_graded', 'ДЗ проверено учителем'), ('homework_deadline', 'Напоминание о дедлайне ДЗ'), ('subscription_expiring', 'Истекает подписка'), ('payment_success', 'Оплата прошла успешно'), ('lesson_reminder', 'Напоминание об уроке'), ('new_homework', 'Новое домашнее задание'), ('absence_alert', 'Серия пропусков ученика'), ('performance_drop_alert', 'Падение успеваемости ученика'), ('group_health_alert', 'Аномалии по группе'), ('grading_backlog', 'Непроверенные ДЗ накопились'), ('inactive_student_alert', 'Неактивный ученик'), ('student_absence_warning', 'Предупреждение о пропусках'), ('control_point_deadline', 'Напоминание о контрольной точке'), ('achievement', 'Достижение/прогресс'), ('student_inactivity_nudge', 'Напоминание об активности'), ('storage_warning', 'Хранилище почти заполнено'), ('storage_limit_exceeded', 'Хранилище заполнено'), ('recording_available', 'Запись урока доступна')], max_length=64),
        ),
    ]
