# Generated by Django 4.2.26 on 2026-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_notification_analytics_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tbank_rebill_id',
            field=models.CharField(blank=True, default='', help_text='RebillId для автоматического продления подписки через T-Bank', max_length=100),
        ),
    ]
