# Generated by Django 4.2.26 on 2026-01-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_tbank_rebill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_meet_access_token',
            field=models.TextField(blank=True, default='', help_text='OAuth2 access token для Google Calendar API (зашифрован)', verbose_name='Google Meet Access Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_meet_connected',
            field=models.BooleanField(default=False, help_text='Флаг показывает, что учитель успешно авторизовал Google Meet', verbose_name='Google Meet подключён'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_meet_email',
            field=models.EmailField(blank=True, default='', help_text='Email аккаунта Google, к которому привязан Meet', max_length=254, verbose_name='Google Meet Email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_meet_refresh_token',
            field=models.TextField(blank=True, default='', help_text='OAuth2 refresh token для обновления access token', verbose_name='Google Meet Refresh Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_meet_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Время истечения access token', null=True, verbose_name='Google Meet Token Expires'),
        ),
    ]
