# Generated by Django 5.2.8 on 2026-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_add_google_meet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='default_lesson_reminder_enabled',
            field=models.BooleanField(default=True, help_text='По умолчанию отправлять напоминания о начале урока'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='default_lesson_reminder_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='За сколько минут до урока отправлять напоминание (5, 10, 15, 30, 60)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='default_notify_to_group_chat',
            field=models.BooleanField(default=True, help_text='Отправлять уведомления в Telegram-группу (если привязана)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='default_notify_to_students_dm',
            field=models.BooleanField(default=True, help_text='Отправлять уведомления ученикам в личные сообщения'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_lesson_link_on_start',
            field=models.BooleanField(default=True, help_text='Отправлять ссылку на урок (Zoom/Meet) когда учитель начинает урок'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_materials_added',
            field=models.BooleanField(default=True, help_text='Уведомлять учеников о добавлении новых материалов к уроку'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_recording_ready',
            field=models.BooleanField(default=True, help_text='Уведомление когда запись урока обработана и доступна'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_student_joined',
            field=models.BooleanField(default=True, help_text='Уведомление когда ученик вступает в группу или становится индивидуальным'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_student_left',
            field=models.BooleanField(default=True, help_text='Уведомление когда ученик покидает группу'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('homework_submitted', 'ДЗ сдано учеником'), ('homework_graded', 'ДЗ проверено учителем'), ('homework_deadline', 'Напоминание о дедлайне ДЗ'), ('subscription_expiring', 'Истекает подписка'), ('payment_success', 'Оплата прошла успешно'), ('lesson_reminder', 'Напоминание об уроке'), ('new_homework', 'Новое домашнее задание'), ('absence_alert', 'Серия пропусков ученика'), ('performance_drop_alert', 'Падение успеваемости ученика'), ('group_health_alert', 'Аномалии по группе'), ('grading_backlog', 'Непроверенные ДЗ накопились'), ('inactive_student_alert', 'Неактивный ученик'), ('student_joined', 'Ученик вступил в группу'), ('student_left', 'Ученик покинул группу'), ('recording_ready', 'Запись урока готова'), ('lesson_link_sent', 'Ссылка на урок отправлена'), ('materials_added', 'Добавлены материалы к уроку'), ('welcome_to_group', 'Добро пожаловать в группу'), ('student_absence_warning', 'Предупреждение о пропусках'), ('control_point_deadline', 'Напоминание о контрольной точке'), ('achievement', 'Достижение/прогресс'), ('student_inactivity_nudge', 'Напоминание об активности'), ('storage_warning', 'Хранилище почти заполнено'), ('storage_limit_exceeded', 'Хранилище заполнено'), ('recording_available', 'Запись урока доступна')], max_length=64),
        ),
    ]
