# Generated by Django 5.2.8 on 2026-01-16 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_notificationsettings_default_lesson_reminder_enabled_and_more'),
        ('schedule', '0028_group_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mute_type', models.CharField(choices=[('group', 'Группа'), ('student', 'Ученик')], help_text='Заглушить группу или конкретного ученика', max_length=20, verbose_name='тип')),
                ('muted_notification_types', models.JSONField(blank=True, default=list, help_text='Список типов уведомлений для заглушки (пусто = все)', verbose_name='типы уведомлений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_mutes', to='schedule.group', verbose_name='группа')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muted_by_teachers', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
                ('user', models.ForeignKey(help_text='Учитель, который заглушает уведомления', on_delete=django.db.models.deletion.CASCADE, related_name='notification_mutes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заглушка уведомлений',
                'verbose_name_plural': 'заглушки уведомлений',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mute_type', 'group')), fields=('user', 'mute_type', 'group'), name='unique_group_mute'), models.UniqueConstraint(condition=models.Q(('mute_type', 'student')), fields=('user', 'mute_type', 'student'), name='unique_student_mute')],
            },
        ),
    ]
