# Generated by Django 5.2.8 on 2026-01-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_notification_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_meet_client_id',
            field=models.CharField(blank=True, default='', help_text='OAuth2 Client ID из Google Cloud Console учителя', max_length=255, verbose_name='Google Meet Client ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_meet_client_secret',
            field=models.CharField(blank=True, default='', help_text='OAuth2 Client Secret из Google Cloud Console учителя', max_length=255, verbose_name='Google Meet Client Secret'),
        ),
    ]
