# Generated by Django 4.2.26 on 2026-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_google_meet_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='zoom_addon_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
