# Generated by Django 5.2.8 on 2026-01-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_subscription_zoom_addon_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='zoom_addon_auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='zoom_addon_payment_method_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='zoom_addon_tbank_rebill_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
