# Generated by Django 4.2.26 on 2026-01-22 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_zoom_addon_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=10)),
                ('source', models.CharField(db_index=True, default='backend', max_length=80)),
                ('code', models.CharField(db_index=True, default='', max_length=80)),
                ('message', models.TextField(default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('request_path', models.CharField(blank=True, default='', max_length=300)),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('process', models.CharField(blank=True, default='', max_length=80)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_system_errors', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['severity', 'last_seen_at'], name='sys_err_sev_ts_idx'), models.Index(fields=['teacher', 'last_seen_at'], name='sys_err_teacher_ts_idx'), models.Index(fields=['fingerprint', 'resolved_at'], name='sys_err_fp_res_idx')],
            },
        ),
    ]
