# Generated by Django 4.2.26 on 2026-01-27 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_add_ended_at_to_lesson'),
        ('accounts', '0034_add_homework_regraded_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_consent',
            field=models.BooleanField(default=False, help_text='Пользователь дал согласие на получение уведомлений в Telegram о занятиях и ДЗ', verbose_name='Согласие на уведомления'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_consent_at',
            field=models.DateTimeField(blank=True, help_text='Когда пользователь дал согласие', null=True, verbose_name='Дата согласия на уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('homework_submitted', 'ДЗ сдано учеником'), ('homework_graded', 'ДЗ проверено учителем'), ('homework_regraded', 'ДЗ переоценено учителем'), ('homework_deadline', 'Напоминание о дедлайне ДЗ'), ('subscription_expiring', 'Истекает подписка'), ('payment_success', 'Оплата прошла успешно'), ('lesson_reminder', 'Напоминание об уроке'), ('new_homework', 'Новое домашнее задание'), ('absence_alert', 'Серия пропусков ученика'), ('performance_drop_alert', 'Падение успеваемости ученика'), ('group_health_alert', 'Аномалии по группе'), ('grading_backlog', 'Непроверенные ДЗ накопились'), ('inactive_student_alert', 'Неактивный ученик'), ('student_joined', 'Ученик вступил в группу'), ('student_left', 'Ученик покинул группу'), ('recording_ready', 'Запись урока готова'), ('lesson_link_sent', 'Ссылка на урок отправлена'), ('materials_added', 'Добавлены материалы к уроку'), ('welcome_to_group', 'Добро пожаловать в группу'), ('student_absence_warning', 'Предупреждение о пропусках'), ('control_point_deadline', 'Напоминание о контрольной точке'), ('achievement', 'Достижение/прогресс'), ('student_inactivity_nudge', 'Напоминание об активности'), ('storage_warning', 'Хранилище почти заполнено'), ('storage_limit_exceeded', 'Хранилище заполнено'), ('recording_available', 'Запись урока доступна')], max_length=64),
        ),
        migrations.CreateModel(
            name='AttendanceAlertRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_absences', models.PositiveIntegerField(default=0, verbose_name='Максимум пропусков на момент прочтения')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alert_reads', to='schedule.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alert_as_student_reads', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alert_reads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прочитанное оповещение о посещаемости',
                'verbose_name_plural': 'Прочитанные оповещения о посещаемости',
                'indexes': [models.Index(fields=['user', 'group'], name='att_alert_read_user_group'), models.Index(fields=['user', 'student'], name='att_alert_read_user_student')],
                'unique_together': {('user', 'student', 'group')},
            },
        ),
    ]
