# Generated by Django 5.2.8 on 2026-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_add_notification_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notified_at',
            field=models.DateTimeField(blank=True, help_text='Когда было отправлено уведомление админу', null=True),
        ),
    ]
