# Generated by Django 5.2.8 on 2026-02-05 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_add_payment_admin_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вход в систему'), ('lesson_conducted', 'Провёл занятие'), ('homework_created', 'Создал ДЗ'), ('homework_graded', 'Проверил ДЗ'), ('recording_uploaded', 'Загрузил запись'), ('student_feedback', 'Комментарий студенту'), ('material_created', 'Создал материал'), ('session_time', 'Время сессии')], db_index=True, max_length=30, verbose_name='тип действия')),
                ('details', models.JSONField(blank=True, default=dict, help_text='{"lesson_id": 123, "minutes": 45, "weight": 10}')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'лог активности преподавателя',
                'verbose_name_plural': 'логи активности преподавателей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'created_at'], name='teacher_activity_main_idx'), models.Index(fields=['action_type', 'created_at'], name='teacher_activity_type_idx'), models.Index(fields=['teacher', 'action_type', 'created_at'], name='teacher_activity_agg_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'сессия преподавателя',
                'verbose_name_plural': 'сессии преподавателей',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['teacher', 'is_active'], name='teacher_session_active_idx'), models.Index(fields=['started_at'], name='teacher_session_date_idx')],
            },
        ),
    ]
