# Generated by Django 5.2.8 on 2026-02-08 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_teacher_activity_heatmap'),
        ('tenants', '0002_create_default_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа, в рамках которой подписка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.school'),
        ),
    ]
