# Generated by Django 5.2.11 on 2026-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_chat_tenant_statusbarmessage_tenant_and_more'),
        ('accounts', '0038_add_school_fk_to_subscription'),
    ]

    operations = [
    ]
