# Generated by Django 4.2.26 on 2026-02-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_add_school_fk_to_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_sessions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сессия на платформе',
                'verbose_name_plural': 'сессии на платформе',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='platform_session_active_idx'), models.Index(fields=['user', 'started_at'], name='platform_session_user_idx'), models.Index(fields=['started_at'], name='platform_session_date_idx')],
            },
        ),
    ]
