# Generated by Django 4.2.26 on 2026-02-07 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Поддомен: slug.lectiospace.ru (только латиница, цифры, дефис)', unique=True)),
                ('name', models.CharField(help_text='Название школы (видно ученикам): "English with Anna"', max_length=200)),
                ('logo_url', models.URLField(blank=True, help_text='URL логотипа школы')),
                ('favicon_url', models.URLField(blank=True, help_text='URL favicon школы')),
                ('primary_color', models.CharField(default='#4F46E5', help_text='Основной цвет бренда (HEX): #4F46E5', max_length=7)),
                ('secondary_color', models.CharField(default='#7C3AED', help_text='Дополнительный цвет (HEX): #7C3AED', max_length=7)),
                ('custom_domain', models.CharField(blank=True, help_text='Свой домен (premium): english-anna.com', max_length=200, null=True, unique=True)),
                ('yookassa_account_id', models.CharField(blank=True, max_length=100)),
                ('yookassa_secret_key', models.CharField(blank=True, max_length=200)),
                ('tbank_terminal_key', models.CharField(blank=True, max_length=100)),
                ('tbank_password', models.CharField(blank=True, max_length=100)),
                ('default_payment_provider', models.CharField(choices=[('yookassa', 'YooKassa'), ('tbank', 'T-Bank')], default='tbank', max_length=20)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200)),
                ('telegram_bot_username', models.CharField(blank=True, max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=990, help_text='Цена месячной подписки для учеников (RUB)', max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=9900, help_text='Цена годовой подписки (RUB)', max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('revenue_share_percent', models.PositiveIntegerField(default=15, help_text='Процент владельцу школы от оплат учеников')),
                ('zoom_enabled', models.BooleanField(default=True)),
                ('google_meet_enabled', models.BooleanField(default=False)),
                ('homework_enabled', models.BooleanField(default=True)),
                ('recordings_enabled', models.BooleanField(default=True)),
                ('finance_enabled', models.BooleanField(default=False)),
                ('concierge_enabled', models.BooleanField(default=False)),
                ('telegram_bot_enabled', models.BooleanField(default=False)),
                ('max_students', models.PositiveIntegerField(default=100, help_text='Максимум учеников в школе')),
                ('max_groups', models.PositiveIntegerField(default=20, help_text='Максимум групп')),
                ('max_teachers', models.PositiveIntegerField(default=5, help_text='Максимум учителей (кроме владельца)')),
                ('max_storage_gb', models.PositiveIntegerField(default=50, help_text='Максимум хранилища (ГБ)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Школа по умолчанию (платформа Lectio Space)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Учитель-владелец школы', on_delete=django.db.models.deletion.PROTECT, related_name='owned_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('teacher', 'Учитель'), ('student', 'Ученик')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник школы',
                'verbose_name_plural': 'Участники школ',
                'unique_together': {('school', 'user')},
            },
        ),
    ]
