# Generated by Django 5.2.11 on 2026-02-17 07:35
# Modified: TenantVideoSettings creation moved to 0004_school_to_tenant

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_school_to_tenant'),
    ]

    operations = [
        # TenantVideoSettings is created in 0004_school_to_tenant
    ]
