param(
    [string]$SSHAlias = 'tp',
    [string]$BaseUrl = 'https://lectio.space',
    [string]$StudentEmail = 'smoke_student_20251216@test.com'
)

$ErrorActionPreference = 'Stop'

function Invoke-RemotePy {
    param([Parameter(Mandatory=$true)][string]$Py)

    $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($Py))

    $remoteScript = @'
set -e
cd /var/www/teaching_panel/teaching_panel

if [ -x ../venv/bin/python ]; then
  PY=../venv/bin/python
else
  echo VENV_PY_NOT_FOUND
  exit 3
fi

"$PY" manage.py shell -c "import base64; exec(base64.b64decode('__B64__').decode('utf-8'))"
'@

    $remoteScript = $remoteScript.Replace('__B64__', $b64) -replace "`r", ""
    $out = $remoteScript | & ssh $SSHAlias bash -s
    if ($LASTEXITCODE -ne 0) {
        throw "Remote python failed (ssh exit=$LASTEXITCODE)"
    }
    return ($out | Out-String)
}

function Get-AccessTokenForEmail {
    param([Parameter(Mandatory=$true)][string]$Email)

    $py = @'
from django.contrib.auth import get_user_model
from rest_framework_simplejwt.tokens import RefreshToken

email = "__EMAIL__"
User = get_user_model()
u = User.objects.get(email=email)
print(str(RefreshToken.for_user(u).access_token))
'@
    $py = $py.Replace('__EMAIL__', $Email)

    $raw = Invoke-RemotePy -Py $py
    $m = [regex]::Match($raw, '[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+')
    if (-not $m.Success) { throw "JWT parse failed for $Email" }
    return $m.Value.Trim()
}

function HttpJson {
    param(
        [Parameter(Mandatory=$true)][ValidateSet('GET','POST','PATCH')][string]$Method,
        [Parameter(Mandatory=$true)][string]$Url,
        [Parameter(Mandatory=$true)][hashtable]$Headers,
        [string]$BodyJson = $null
    )
    try {
        if ($Method -eq 'GET') {
            $resp = Invoke-WebRequest -Method Get -Uri $Url -Headers $Headers -TimeoutSec 25
        } elseif ($Method -eq 'POST') {
            $resp = Invoke-WebRequest -Method Post -Uri $Url -Headers $Headers -ContentType 'application/json' -Body ($BodyJson ?? '{}') -TimeoutSec 25
        } else {
            $resp = Invoke-WebRequest -Method Patch -Uri $Url -Headers $Headers -ContentType 'application/json' -Body ($BodyJson ?? '{}') -TimeoutSec 25
        }
        $json = $null
        try { $json = $resp.Content | ConvertFrom-Json } catch { }
        return [PSCustomObject]@{ ok=$true; status=$resp.StatusCode; json=$json; raw=$resp.Content }
    } catch {
        $status = $null
        $raw = $null
        try { $status = [int]$_.Exception.Response.StatusCode.value__ } catch { }
        try {
            $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
            $raw = $reader.ReadToEnd()
        } catch { }
        return [PSCustomObject]@{ ok=$false; status=$status; json=$null; raw=$raw }
    }
}

Write-Host "=== Create & publish temp homework, enroll student ===" -ForegroundColor Cyan
$py = @'
import json
from django.utils import timezone
from django.contrib.auth import get_user_model
from schedule.models import Group
from homework.models import Homework, Question, Choice

student_email = "__STUDENT_EMAIL__"
User = get_user_model()
student = User.objects.get(email=student_email)
teacher = User.objects.filter(role='teacher').order_by('id').first()
if teacher is None:
    raise RuntimeError('No teacher found')

# Pick existing teacher group, else create one
grp = Group.objects.filter(teacher=teacher).order_by('created_at').first()
if grp is None:
    grp = Group.objects.create(name='SMOKE GROUP', teacher=teacher)

grp.students.add(student)

hw = Homework.objects.create(
    teacher=teacher,
    title=f"SMOKE HW {timezone.now().strftime('%Y-%m-%d %H:%M:%S')}",
    description='autogenerated smoke homework',
    status='draft',
)

q1 = Question.objects.create(
    homework=hw,
    prompt='2+2=?',
    question_type='SINGLE_CHOICE',
    points=3,
    order=1,
    config={},
)
Choice.objects.create(question=q1, text='3', is_correct=False)
Choice.objects.create(question=q1, text='4', is_correct=True)

Question.objects.create(
    homework=hw,
    prompt='Сопоставь буквы и числа',
    question_type='MATCHING',
    points=5,
    order=2,
    config={
        'pairs': [
            {'id': 'p1', 'left': 'A', 'right': '1'},
            {'id': 'p2', 'left': 'B', 'right': '2'},
        ]
    },
)

# publish
hw.status = 'published'
hw.published_at = timezone.now()
hw.save(update_fields=['status','published_at'])

print(json.dumps({'teacher_email': teacher.email, 'group_id': grp.id, 'homework_id': hw.id}))
'@
$py = $py.Replace('__STUDENT_EMAIL__', $StudentEmail)
$raw = Invoke-RemotePy -Py $py
$line = ($raw -split "`n" | Where-Object { $_.Trim().StartsWith('{') } | Select-Object -First 1)
if (-not $line) { throw "Failed to parse homework creation output" }
$created = $line | ConvertFrom-Json

$teacherEmail = [string]$created.teacher_email
$homeworkId = [int]$created.homework_id
Write-Host "Created homework_id=$homeworkId teacher=$teacherEmail" -ForegroundColor DarkGray

Write-Host "=== Verify student sees homework & points ===" -ForegroundColor Cyan
$studentTok = Get-AccessTokenForEmail -Email $StudentEmail
$headers = @{ Authorization = "Bearer $studentTok" }

$list = HttpJson -Method GET -Url "$BaseUrl/api/homework/" -Headers $headers
if (-not $list.ok) { throw "student /api/homework failed status=$($list.status)" }
$items = @()
if ($list.json.results) { $items = @($list.json.results) } elseif ($list.json -is [System.Collections.IEnumerable]) { $items = @($list.json) }
$found = $items | Where-Object { $_.id -eq $homeworkId } | Select-Object -First 1
if (-not $found) {
    throw "Created homework not visible to student (homework_id=$homeworkId)"
}

$detail = HttpJson -Method GET -Url "$BaseUrl/api/homework/$homeworkId/" -Headers $headers
if (-not $detail.ok) { throw "student /api/homework/{id} failed status=$($detail.status)" }

$q0 = $detail.json.questions | Select-Object -First 1
if (-not $q0) { throw "No questions in homework detail" }

$hasPoints = $q0.PSObject.Properties.Name -contains 'points'
Write-Output ("STUDENT_HOMEWORK_VISIBLE=1")
Write-Output ("STUDENT_QUESTION_HAS_POINTS={0}" -f $hasPoints)
if ($hasPoints) {
    Write-Output ("STUDENT_QUESTION_POINTS={0}" -f $q0.points)
}

Write-Host "=== Create submission, answer, submit ===" -ForegroundColor Cyan
$createSub = HttpJson -Method POST -Url "$BaseUrl/api/submissions/" -Headers $headers -BodyJson ((@{ homework = $homeworkId } | ConvertTo-Json))
if (-not $createSub.ok) { throw "student create submission failed status=$($createSub.status) raw=$($createSub.raw)" }
$submissionId = [int]$createSub.json.id
if (-not $submissionId) { throw "submission id missing" }
Write-Host "submission_id=$submissionId" -ForegroundColor DarkGray

$questions = @($detail.json.questions)
$qSingle = $questions | Where-Object { $_.question_type -eq 'SINGLE_CHOICE' } | Select-Object -First 1
$qMatch = $questions | Where-Object { $_.question_type -eq 'MATCHING' } | Select-Object -First 1
if (-not $qSingle) { throw "SINGLE_CHOICE question not found in student payload" }
if (-not $qMatch) { throw "MATCHING question not found in student payload" }

$choiceCorrect = @($qSingle.choices) | Where-Object { $_.text -eq '4' } | Select-Object -First 1
if (-not $choiceCorrect) { throw "Correct choice '4' not found" }

$answersObj = @{}
$answersObj["$($qSingle.id)"] = [int]$choiceCorrect.id
$answersObj["$($qMatch.id)"] = @{ p1 = '1'; p2 = '2' }

$savePayload = @{ answers = $answersObj } | ConvertTo-Json -Depth 10
$save = HttpJson -Method PATCH -Url "$BaseUrl/api/submissions/$submissionId/answer/" -Headers $headers -BodyJson $savePayload
if (-not $save.ok) { throw "student save answers failed status=$($save.status) raw=$($save.raw)" }
Write-Output ("SUBMISSION_SAVED_TOTAL_SCORE={0}" -f $save.json.total_score)

$submitPayload = (@{ } | ConvertTo-Json)
$submit = HttpJson -Method POST -Url "$BaseUrl/api/submissions/$submissionId/submit/" -Headers $headers -BodyJson $submitPayload
if (-not $submit.ok) { throw "student submit failed status=$($submit.status) raw=$($submit.raw)" }
Write-Output ("SUBMISSION_STATUS={0}" -f $submit.json.status)
Write-Output ("SUBMISSION_TOTAL_SCORE={0}" -f $submit.json.total_score)
Write-Output ("SUBMISSION_MAX_SCORE={0}" -f $submit.json.max_score)

Write-Host "=== Teacher can see submission (no grading) ===" -ForegroundColor Cyan
$teacherTok = Get-AccessTokenForEmail -Email $teacherEmail
$teacherHeaders = @{ Authorization = "Bearer $teacherTok" }

$tList = HttpJson -Method GET -Url "$BaseUrl/api/submissions/?homework=$homeworkId" -Headers $teacherHeaders
if (-not $tList.ok) { throw "teacher submissions list failed status=$($tList.status) raw=$($tList.raw)" }
$tItems = @()
if ($tList.json.results) { $tItems = @($tList.json.results) } elseif ($tList.json -is [System.Collections.IEnumerable]) { $tItems = @($tList.json) }
$tFound = $tItems | Where-Object { $_.id -eq $submissionId } | Select-Object -First 1
if (-not $tFound) { throw "teacher does not see submission_id=$submissionId for homework=$homeworkId" }
Write-Output "TEACHER_SUBMISSION_VISIBLE=1"

$tDetail = HttpJson -Method GET -Url "$BaseUrl/api/submissions/$submissionId/" -Headers $teacherHeaders
if (-not $tDetail.ok) { throw "teacher submission detail failed status=$($tDetail.status) raw=$($tDetail.raw)" }
$ans0 = $tDetail.json.answers | Select-Object -First 1
if (-not $ans0) { throw "teacher submission detail missing answers" }
$hasQP = $ans0.PSObject.Properties.Name -contains 'question_points'
Write-Output ("TEACHER_ANSWER_HAS_QUESTION_POINTS={0}" -f $hasQP)

Write-Host "OK: homework flow smoke done" -ForegroundColor Green
