# Generated by Django 4.2.26 on 2026-02-05 12:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0031_add_soft_delete_to_recording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Текущий баланс. Положительный = предоплата, отрицательный = долг', max_digits=10, verbose_name='баланс')),
                ('default_lesson_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Стандартная стоимость одного урока для этого ученика', max_digits=8, verbose_name='стоимость урока')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='валюта')),
                ('debt_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Максимальный допустимый долг. 0 = без лимита', max_digits=10, verbose_name='лимит долга')),
                ('notes', models.TextField(blank=True, help_text='Заметки учителя о финансах ученика', verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_financial_profiles', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student_wallets', to=settings.AUTH_USER_MODEL, verbose_name='учитель')),
            ],
            options={
                'verbose_name': 'финансовый профиль ученика',
                'verbose_name_plural': 'финансовые профили учеников',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Положительное = приход, отрицательное = расход', max_digits=10, verbose_name='сумма')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Пополнение'), ('LESSON_CHARGE', 'Списание за урок'), ('ADJUSTMENT', 'Корректировка'), ('REFUND', 'Возврат')], max_length=20, verbose_name='тип')),
                ('is_group_lesson', models.BooleanField(default=False, help_text='True если урок был групповым (>1 ученика)', verbose_name='групповой урок')),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если задано — использовалась вместо default_lesson_price (скидка, пробный и т.д.)', max_digits=8, null=True, verbose_name='изменённая цена')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('auto_created', models.BooleanField(default=False, help_text='True если создано автоматически при завершении урока', verbose_name='автоматически')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('lesson', models.ForeignKey(blank=True, help_text='Урок, за который списаны/возвращены деньги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='schedule.lesson', verbose_name='связанный урок')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.studentfinancialprofile', verbose_name='кошелёк')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='finance_tra_wallet__4bc174_idx'), models.Index(fields=['lesson'], name='finance_tra_lesson__f77bc5_idx'), models.Index(fields=['transaction_type', '-created_at'], name='finance_tra_transac_4b3fc4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studentfinancialprofile',
            index=models.Index(fields=['teacher', 'student'], name='finance_stu_teacher_82f7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfinancialprofile',
            index=models.Index(fields=['balance'], name='finance_stu_balance_64061d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentfinancialprofile',
            unique_together={('student', 'teacher')},
        ),
    ]
