# Generated by Django 5.2.8 on 2026-02-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('tenants', '0002_create_default_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfinancialprofile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_profiles', to='tenants.school'),
        ),
    ]
