# Generated by Django 5.2.8 on 2025-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('zoom_user_id', models.CharField(blank=True, max_length=255)),
                ('max_concurrent_meetings', models.IntegerField(default=1)),
                ('current_meetings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zoom Account',
                'verbose_name_plural': 'Zoom Accounts',
                'ordering': ['current_meetings', '-last_used_at'],
            },
        ),
    ]
