# Generated by Django 5.2.8 on 2025-11-17 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_pool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomaccount',
            name='preferred_teachers',
            field=models.ManyToManyField(blank=True, help_text='Преподаватели, которым этот аккаунт назначается приоритетно', limit_choices_to={'role': 'teacher'}, related_name='preferred_zoom_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
