# Generated by ChatGPT on 2025-11-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_pool', '0002_zoomaccount_preferred_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomPoolUsageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_in_use', models.IntegerField(default=0)),
                ('peak_in_use', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zoom Pool Usage Metric',
                'verbose_name_plural': 'Zoom Pool Usage Metrics',
            },
        ),
    ]
