# Generated by ChatGPT on 2025-11-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_pool', '0003_zoompoolusagemetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoompoolusagemetrics',
            name='current_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zoompoolusagemetrics',
            name='peak_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
