# Generated by ChatGPT on 2025-11-18
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_pool', '0004_zoompoolusagemetrics_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoompoolusagemetrics',
            name='stats_month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
