# Generated by Django 5.2.8 on 2025-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_pool', '0005_zoompoolusagemetrics_stats_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomaccount',
            name='zoom_account_id',
            field=models.CharField(blank=True, default='', help_text='Account ID из Zoom Server-to-Server OAuth App', max_length=255),
        ),
        migrations.AlterField(
            model_name='zoomaccount',
            name='api_key',
            field=models.CharField(help_text='Client ID из Zoom Server-to-Server OAuth App', max_length=255),
        ),
        migrations.AlterField(
            model_name='zoomaccount',
            name='api_secret',
            field=models.CharField(help_text='Client Secret из Zoom Server-to-Server OAuth App', max_length=255),
        ),
        migrations.AlterField(
            model_name='zoomaccount',
            name='zoom_user_id',
            field=models.CharField(blank=True, default='me', help_text='User ID в Zoom (обычно "me" или email)', max_length=255),
        ),
    ]
