# Generated by Django 5.2.11 on 2026-02-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_school_to_tenant'),
        ('zoom_pool', '0005_zoompoolusagemetrics_stats_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_pool_accounts', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AddField(
            model_name='zoompoolusagemetrics',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_pool_metrics', to='tenants.tenant', verbose_name='Тенант'),
        ),
    ]
