# Generated by Django 5.2.11 on 2026-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_pool', '0006_add_zoom_account_id'),
        ('zoom_pool', '0006_zoomaccount_tenant_zoompoolusagemetrics_tenant'),
    ]

    operations = [
    ]
