# Generated by Django 5.2.8 on 2025-11-13 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название группы')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_groups', to=settings.AUTH_USER_MODEL, verbose_name='студенты')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('start_time', models.DateTimeField(verbose_name='время начала')),
                ('end_time', models.DateTimeField(verbose_name='время окончания')),
                ('topics', models.TextField(blank=True, help_text='Темы, которые будут рассмотрены на уроке', verbose_name='темы урока')),
                ('location', models.CharField(blank=True, help_text='Адрес или название аудитории', max_length=300, verbose_name='место проведения')),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID встречи Zoom')),
                ('zoom_join_url', models.URLField(blank=True, null=True, verbose_name='ссылка на Zoom')),
                ('zoom_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='пароль Zoom')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.group', verbose_name='группа')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_lessons', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('excused', 'Уважительная причина')], default='absent', max_length=10, verbose_name='статус')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('marked_at', models.DateTimeField(auto_now=True, verbose_name='время отметки')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='студент')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedule.lesson', verbose_name='занятие')),
            ],
            options={
                'verbose_name': 'посещаемость',
                'verbose_name_plural': 'посещаемость',
                'ordering': ['lesson__start_time'],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
