# Generated by Django 5.2.8 on 2025-11-13 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка для запуска (преподаватель)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка для входа (студенты)'),
        ),
        migrations.CreateModel(
            name='RecurringLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], help_text='0 = Понедельник, 6 = Воскресенье', verbose_name='день недели')),
                ('week_type', models.CharField(choices=[('ALL', 'Каждая неделя'), ('UPPER', 'Верхняя неделя'), ('LOWER', 'Нижняя неделя')], default='ALL', help_text='Для семестров с чередованием недель', max_length=10, verbose_name='тип недели')),
                ('start_time', models.TimeField(verbose_name='время начала')),
                ('end_time', models.TimeField(verbose_name='время окончания')),
                ('start_date', models.DateField(verbose_name='дата начала действия')),
                ('end_date', models.DateField(verbose_name='дата окончания действия')),
                ('topics', models.TextField(blank=True, help_text='Стандартные темы для этого регулярного урока', verbose_name='темы урока')),
                ('location', models.CharField(blank=True, help_text='Адрес или название аудитории', max_length=300, verbose_name='место проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_lessons', to='schedule.group', verbose_name='группа')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_teaching_lessons', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'регулярное занятие',
                'verbose_name_plural': 'регулярные занятия',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ZoomAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Zoom License 1', max_length=200, verbose_name='название аккаунта')),
                ('api_key', models.CharField(max_length=255, verbose_name='API ключ')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API секрет')),
                ('zoom_user_id', models.CharField(max_length=255, verbose_name='Zoom User ID')),
                ('is_busy', models.BooleanField(db_index=True, default=False, verbose_name='занят')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('current_lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_zoom_account', to='schedule.lesson', verbose_name='текущее занятие')),
            ],
            options={
                'verbose_name': 'Zoom аккаунт',
                'verbose_name_plural': 'Zoom аккаунты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='zoom_account_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_history', to='schedule.zoomaccount', verbose_name='использованный Zoom аккаунт'),
        ),
    ]
