# Generated by Django 5.2.8 on 2025-11-13 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_lesson_zoom_start_url_alter_lesson_zoom_join_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='URL записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='schedule.lesson', verbose_name='урок')),
            ],
            options={
                'verbose_name': 'запись урока',
                'verbose_name_plural': 'записи уроков',
                'ordering': ['-created_at'],
            },
        ),
    ]
