# Generated by Django 5.2.8 on 2025-11-13 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_lessonrecording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time'], name='schedule_le_start_t_73e2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'start_time'], name='schedule_le_teacher_1b6951_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'start_time'], name='schedule_le_group_i_6afb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringlesson',
            index=models.Index(fields=['teacher', 'day_of_week'], name='schedule_re_teacher_5496f7_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringlesson',
            index=models.Index(fields=['group', 'day_of_week'], name='schedule_re_group_i_d74fbe_idx'),
        ),
    ]
