# Generated by Django 5.2.8 on 2025-11-13 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lesson_schedule_le_start_t_73e2a5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lesson', 'student'], name='schedule_at_lesson__4c13ce_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status'], name='schedule_at_student_d8c1d6_idx'),
        ),
    ]
