# Generated by Django 5.2.8 on 2025-11-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_attendance_schedule_at_lesson__4c13ce_idx_and_more'),
        ('zoom_pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='zoom_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lessons', to='zoom_pool.zoomaccount', verbose_name='назначенный Zoom аккаунт'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='zoom_account_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_history', to='schedule.zoomaccount', verbose_name='использованный Zoom аккаунт (старое)'),
        ),
    ]
