# Generated by Django 5.2.8 on 2025-11-14 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_lesson_zoom_account_alter_lesson_zoom_account_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('lesson_start', 'Запуск урока'), ('lesson_create', 'Создание урока'), ('lesson_update', 'Обновление урока'), ('lesson_delete', 'Удаление урока'), ('zoom_account_acquire', 'Захват Zoom аккаунта'), ('zoom_account_release', 'Освобождение Zoom аккаунта')], max_length=50, verbose_name='действие')),
                ('resource_type', models.CharField(max_length=50, verbose_name='тип ресурса')),
                ('resource_id', models.IntegerField(blank=True, null=True, verbose_name='ID ресурса')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='детали')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'записи аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='schedule_au_user_id_bb3369_idx'), models.Index(fields=['action', '-timestamp'], name='schedule_au_action_b731bc_idx'), models.Index(fields=['resource_type', 'resource_id'], name='schedule_au_resourc_682d84_idx')],
            },
        ),
    ]
