# Generated by Django 5.2.8 on 2025-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrecording',
            name='url',
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='archive_key',
            field=models.CharField(blank=True, help_text='Путь к файлу в S3/Azure: recordings/{lesson_id}/{recording_id}.mp4', max_length=500, verbose_name='ключ в хранилище'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='archive_size_bytes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='размер архива'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='archive_url',
            field=models.URLField(blank=True, help_text='Постоянная ссылка на запись в облачном хранилище (S3/Azure Blob)', verbose_name='архивная ссылка'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата архивирования'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='download_url',
            field=models.URLField(blank=True, verbose_name='ссылка для скачивания'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='длительность (секунды)'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='размер файла (байты)'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='play_url',
            field=models.URLField(blank=True, verbose_name='ссылка для просмотра'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='recording_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='окончание записи'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='recording_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало записи'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('completed', 'Готова'), ('archived', 'Архивирована'), ('failed', 'Ошибка')], default='processing', max_length=20, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='zoom_recording_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID записи Zoom'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
