# Generated by Django 4.2.26 on 2025-11-25 19:20

from django.db import migrations, models
from django.db import connection


def _add_invite_code_column_and_constraint(schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        schema_editor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'schedule_group'
                      AND column_name = 'invite_code'
                ) THEN
                    ALTER TABLE schedule_group
                    ADD COLUMN invite_code varchar(8);
                END IF;

                BEGIN
                    ALTER TABLE schedule_group
                    ADD CONSTRAINT schedule_group_invite_code_key UNIQUE (invite_code);
                EXCEPTION
                    WHEN duplicate_object THEN NULL;
                END;
            END $$;
            """
        )
    else:
        # Generic fallback (e.g. sqlite): add column if missing
        cursor = schema_editor.connection.cursor()
        existing_cols = []
        try:
            cursor.execute("PRAGMA table_info(schedule_group);")
            existing_cols = [r[1] for r in cursor.fetchall()]
        except Exception:
            pass
        if 'invite_code' not in existing_cols:
            schema_editor.execute("ALTER TABLE schedule_group ADD COLUMN invite_code varchar(8);")
        # Unique constraint via unique index (ALTER TABLE ADD CONSTRAINT not universally supported)
        # SQLite supports IF NOT EXISTS for indexes.
        schema_editor.execute("CREATE UNIQUE INDEX IF NOT EXISTS schedule_group_invite_code_key ON schedule_group(invite_code);")


def _remove_invite_code_column_and_constraint(schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        schema_editor.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints
                    WHERE table_name = 'schedule_group'
                      AND constraint_name = 'schedule_group_invite_code_key'
                ) THEN
                    ALTER TABLE schedule_group
                    DROP CONSTRAINT schedule_group_invite_code_key;
                END IF;

                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'schedule_group'
                      AND column_name = 'invite_code'
                ) THEN
                    ALTER TABLE schedule_group
                    DROP COLUMN invite_code;
                END IF;
            END $$;
            """
        )
    else:
        # Drop unique index then (optionally) leave column or recreate table (dropping column in sqlite is complex).
        # For simplicity we only drop index; column removal requires table rebuild.
        schema_editor.execute("DROP INDEX IF EXISTS schedule_group_invite_code_key;")

def forwards(apps, schema_editor):
    _add_invite_code_column_and_constraint(schema_editor)


def backwards(apps, schema_editor):
    _remove_invite_code_column_and_constraint(schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_lessonrecording_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(
                blank=True,
                help_text='Уникальный код для присоединения учеников к группе',
                max_length=8,
                null=True,
                unique=True,
                verbose_name='код приглашения',
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
