# Generated by Django 4.2.26 on 2025-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_lessonrecording_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Уникальный код для присоединения учеников к группе', max_length=8, null=True, unique=True, verbose_name='код приглашения'),
        ),
    ]
