# Generated by Django 4.2.26 on 2025-12-02 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0009_group_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='record_lesson',
            field=models.BooleanField(default=False, help_text='Автоматически записывать урок в Zoom и сохранять в Google Drive', verbose_name='записывать урок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recording_available_for_days',
            field=models.IntegerField(default=90, help_text='Сколько дней запись будет доступна ученикам (0 = бессрочно)', verbose_name='доступность записи (дней)'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Дата автоматического удаления записи', null=True, verbose_name='доступна до'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Уникальный ID файла в Google Drive для прямого доступа', max_length=100, verbose_name='Google Drive File ID'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, help_text='ID папки в Google Drive где хранится запись', max_length=100, verbose_name='Google Drive Folder ID'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='storage_provider',
            field=models.CharField(choices=[('gdrive', 'Google Drive'), ('s3', 'AWS S3'), ('azure', 'Azure Blob'), ('local', 'Локальное хранилище')], default='gdrive', max_length=20, verbose_name='провайдер хранилища'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Ссылка на миниатюру/обложку видео', verbose_name='превью записи'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Сколько раз запись была просмотрена', verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='archive_key',
            field=models.CharField(blank=True, help_text='ID файла в Google Drive или путь в S3/Azure', max_length=500, verbose_name='ключ в хранилище'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='archive_url',
            field=models.URLField(blank=True, help_text='Постоянная ссылка на запись в облачном хранилище', verbose_name='архивная ссылка'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('ready', 'Готова'), ('archived', 'Архивирована'), ('failed', 'Ошибка'), ('deleted', 'Удалена')], default='processing', max_length=20, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('theory', 'Теория (перед уроком)'), ('notes', 'Конспект (после урока)')], help_text='Теория (для чтения перед уроком) или конспект (после урока)', max_length=10, verbose_name='тип материала')),
                ('title', models.CharField(help_text='Название материала', max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Краткое описание содержания', verbose_name='описание')),
                ('file_url', models.URLField(help_text='URL файла в Google Drive или другом хранилище', max_length=500, verbose_name='ссылка на файл')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='имя файла')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='размер файла (байты)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='schedule.lesson', verbose_name='урок')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'учебный материал',
                'verbose_name_plural': 'учебные материалы',
                'ordering': ['material_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quota_bytes', models.BigIntegerField(default=5368709120, help_text='Общий лимит хранилища в байтах', verbose_name='общая квота (байты)')),
                ('used_bytes', models.BigIntegerField(default=0, help_text='Фактически использованный объем', verbose_name='использовано (байты)')),
                ('recordings_count', models.IntegerField(default=0, help_text='Общее количество записей', verbose_name='количество записей')),
                ('purchased_gb', models.IntegerField(default=0, help_text='Суммарно докуплено гигабайт сверх базовой квоты', verbose_name='докуплено GB')),
                ('warning_sent', models.BooleanField(default=False, help_text='Флаг отправки предупреждения о превышении 80%', verbose_name='предупреждение отправлено')),
                ('last_warning_at', models.DateTimeField(blank=True, null=True, verbose_name='дата последнего предупреждения')),
                ('quota_exceeded', models.BooleanField(default=False, help_text='Флаг превышения квоты', verbose_name='квота превышена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'квота хранилища',
                'verbose_name_plural': 'квоты хранилища',
                'ordering': ['-used_bytes'],
                'indexes': [models.Index(fields=['teacher'], name='schedule_te_teacher_dab515_idx'), models.Index(fields=['quota_exceeded'], name='schedule_te_quota_e_af0eb0_idx'), models.Index(fields=['-used_bytes'], name='schedule_te_used_by_3a5c05_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='дата просмотра')),
                ('duration_seconds', models.IntegerField(default=0, help_text='Сколько времени ученик провел с материалом', verbose_name='длительность просмотра (секунды)')),
                ('completed', models.BooleanField(default=False, help_text='Ученик полностью изучил материал', verbose_name='завершен')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='schedule.lessonmaterial', verbose_name='материал')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'просмотр материала',
                'verbose_name_plural': 'просмотры материалов',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['material', 'student'], name='schedule_ma_materia_c36b5e_idx'), models.Index(fields=['student', 'viewed_at'], name='schedule_ma_student_7a03c9_idx')],
                'unique_together': {('material', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['lesson', 'material_type'], name='schedule_le_lesson__dcda3d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='schedule_le_uploade_1aec18_idx'),
        ),
    ]
