# Generated by Django 4.2.26 on 2025-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_lesson_record_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecording',
            name='recording_type',
            field=models.CharField(default='shared_screen_with_speaker_view', help_text='Тип Zoom записи: shared_screen_with_speaker_view, audio_only и т.д.', max_length=50, verbose_name='тип записи'),
        ),
    ]
