# Generated by Django 4.2.26 on 2025-12-02 16:49

from django.conf import settings
from django.db import migrations, models


def seed_default_access(apps, schema_editor):
    LessonRecording = apps.get_model('schedule', 'LessonRecording')
    Group = apps.get_model('schedule', 'Group')

    for recording in LessonRecording.objects.select_related('lesson__group').all():
        lesson = getattr(recording, 'lesson', None)
        group = getattr(lesson, 'group', None) if lesson else None
        if group:
            recording.allowed_groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_lessonrecording_recording_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecording',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='recording_access', to='schedule.group', verbose_name='доступные группы'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='recording_access', to=settings.AUTH_USER_MODEL, verbose_name='доступные студенты'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='visibility',
            field=models.CharField(choices=[('lesson_group', 'Только группа урока'), ('all_teacher_groups', 'Все группы преподавателя'), ('custom_groups', 'Выбранные группы'), ('custom_students', 'Выбранные ученики')], default='lesson_group', help_text='Определяет, кому доступна запись', max_length=32, verbose_name='видимость'),
        ),
        migrations.RunPython(seed_default_access, migrations.RunPython.noop),
    ]
