# Generated by Django 4.2.26 on 2025-12-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_lessonrecording_allowed_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecording',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Урок, к которому привязана запись (может быть пустым для standalone записей)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='schedule.lesson', verbose_name='урок'),
        ),
    ]
