# Generated by Django 4.2.26 on 2025-12-05 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0013_make_lesson_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Название предмета/дисциплины', max_length=200, verbose_name='предмет')),
                ('invite_code', models.CharField(db_index=True, help_text='Уникальный 8-символьный код для приглашения одного ученика', max_length=8, unique=True, verbose_name='код приглашения')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Был ли код использован для приглашения ученика', verbose_name='использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='дата использования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='individual_invite_codes', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
                ('used_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_individual_subjects', to=settings.AUTH_USER_MODEL, verbose_name='использован учеником')),
            ],
            options={
                'verbose_name': 'индивидуальный инвайт-код',
                'verbose_name_plural': 'индивидуальные инвайт-коды',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'is_used'], name='schedule_in_teacher_7762a6_idx'), models.Index(fields=['used_by'], name='schedule_in_used_by_6295cc_idx'), models.Index(fields=['invite_code'], name='schedule_in_invite__befbc6_idx')],
            },
        ),
    ]
