# Generated by Django 4.2.26 on 2025-12-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_individualinvitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_quick_lesson',
            field=models.BooleanField(default=False, help_text='Урок создан через "Быстрый урок" и не должен отображаться в расписании', verbose_name='быстрый урок'),
        ),
    ]
