# Generated by Django 5.2.8 on 2025-12-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_lesson_is_quick_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringlesson',
            name='telegram_announce_enabled',
            field=models.BooleanField(default=False, help_text='Отправлять анонс заранее (утром в день урока)', verbose_name='Анонс урока'),
        ),
        migrations.AddField(
            model_name='recurringlesson',
            name='telegram_announce_time',
            field=models.TimeField(blank=True, default=None, help_text='Во сколько отправить анонс в день урока', null=True, verbose_name='Время анонса'),
        ),
        migrations.AddField(
            model_name='recurringlesson',
            name='telegram_group_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID группы в Telegram (бот должен быть добавлен в группу)', max_length=50, verbose_name='Chat ID Telegram-группы'),
        ),
        migrations.AddField(
            model_name='recurringlesson',
            name='telegram_notify_enabled',
            field=models.BooleanField(default=False, help_text='Отправлять уведомления о начале урока', verbose_name='Telegram-уведомления'),
        ),
        migrations.AddField(
            model_name='recurringlesson',
            name='telegram_notify_minutes',
            field=models.PositiveIntegerField(default=10, help_text='За сколько минут до начала отправлять уведомление (5, 10, 15, 30)', verbose_name='За сколько минут'),
        ),
        migrations.AddField(
            model_name='recurringlesson',
            name='telegram_notify_to_group',
            field=models.BooleanField(default=True, help_text='Отправлять уведомление в Telegram-группу', verbose_name='В группу'),
        ),
        migrations.AddField(
            model_name='recurringlesson',
            name='telegram_notify_to_students',
            field=models.BooleanField(default=False, help_text='Отправлять личные сообщения ученикам', verbose_name='В личку'),
        ),
        migrations.CreateModel(
            name='LessonNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder', 'Напоминание'), ('announce', 'Анонс')], max_length=20, verbose_name='тип уведомления')),
                ('lesson_date', models.DateField(verbose_name='дата урока')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='количество получателей')),
                ('error_message', models.TextField(blank=True, default='', help_text='Сообщение об ошибке, если уведомление не удалось отправить', verbose_name='ошибка')),
                ('recurring_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='schedule.recurringlesson', verbose_name='регулярный урок')),
            ],
            options={
                'verbose_name': 'лог уведомления',
                'verbose_name_plural': 'логи уведомлений',
                'indexes': [models.Index(fields=['lesson_date', 'notification_type'], name='schedule_le_lesson__5af4f7_idx')],
                'unique_together': {('recurring_lesson', 'notification_type', 'lesson_date')},
            },
        ),
    ]
