# Generated by Django 4.2.26 on 2025-12-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_telegram_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringLessonTelegramBindCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='код')),
                ('expires_at', models.DateTimeField(verbose_name='истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='использован')),
                ('used_chat_id', models.CharField(blank=True, default='', max_length=50, verbose_name='chat_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('recurring_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bind_codes', to='schedule.recurringlesson', verbose_name='регулярный урок')),
            ],
            options={
                'verbose_name': 'код привязки Telegram',
                'verbose_name_plural': 'коды привязки Telegram',
                'indexes': [models.Index(fields=['expires_at'], name='schedule_re_expires_c053da_idx'), models.Index(fields=['used_at'], name='schedule_re_used_at_556b1d_idx')],
            },
        ),
    ]
