# Generated by Django 5.2.8 on 2025-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_recurringlessontelegrambindcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='recurringlesson',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='название'),
        ),
    ]
