# Generated by Django 5.2.8 on 2025-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_lesson_title_optional'),
    ]

    operations = [
        # invite_code already added by migration 0009 via RunPython
        migrations.AlterField(
            model_name='lesson',
            name='zoom_join_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка для входа (студенты)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='zoom_start_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='ссылка для запуска (преподаватель)'),
        ),
    ]
