# Generated by Django 5.2.8 on 2026-01-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_increase_zoom_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Уникальный код для присоединения учеников к группе', max_length=8, null=True, unique=True, verbose_name='код приглашения'),
        ),
        migrations.CreateModel(
            name='LessonTranscriptStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_json', models.JSONField(default=dict, help_text='JSON со статистикой: speakers, mentions, timeline', verbose_name='данные анализа')),
                ('teacher_talk_time_percent', models.FloatField(default=0, verbose_name='% времени учителя')),
                ('student_talk_time_percent', models.FloatField(default=0, verbose_name='% времени учеников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата анализа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_stats', to='schedule.lesson', verbose_name='урок')),
            ],
            options={
                'verbose_name': 'статистика транскрипта',
                'verbose_name_plural': 'статистика транскриптов',
            },
        ),
    ]
