# Generated by Django 4.2.26 on 2026-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_group_invite_code_lessontranscriptstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecording',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Название standalone видео (если запись не привязана к уроку)', max_length=255, verbose_name='название'),
        ),
    ]
