# Generated by Django 4.2.26 on 2026-01-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_add_teacher_to_lesson_recording'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmaterial',
            options={'ordering': ['order', 'material_type', '-uploaded_at'], 'verbose_name': 'учебный материал', 'verbose_name_plural': 'учебные материалы'},
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='material_access', to='schedule.group', verbose_name='доступные группы'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='content',
            field=models.TextField(blank=True, help_text='Текстовый контент конспекта (Markdown или HTML)', verbose_name='содержимое'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='ID файла в Google Drive', max_length=100, verbose_name='Google Drive File ID'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='miro_board_id',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор доски в Miro', max_length=100, verbose_name='ID доски Miro'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='miro_board_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на доску Miro', max_length=500, verbose_name='ссылка на доску Miro'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='miro_embed_url',
            field=models.URLField(blank=True, help_text='Ссылка для встраивания доски (iframe)', max_length=500, verbose_name='embed ссылка Miro'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='miro_thumbnail_url',
            field=models.URLField(blank=True, help_text='Ссылка на миниатюру доски', max_length=500, verbose_name='превью доски Miro'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AddField(
            model_name='lessonmaterial',
            name='visibility',
            field=models.CharField(choices=[('lesson_group', 'Только группа урока'), ('all_teacher_groups', 'Все группы преподавателя'), ('custom_groups', 'Выбранные группы')], default='lesson_group', help_text='Кому доступен материал', max_length=32, verbose_name='видимость'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL файла в Google Drive или другом хранилище', max_length=500, verbose_name='ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Урок, к которому привязан материал (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='schedule.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='material_type',
            field=models.CharField(choices=[('theory', 'Теория (перед уроком)'), ('notes', 'Конспект (после урока)'), ('miro', 'Доска Miro'), ('document', 'Документ'), ('link', 'Ссылка'), ('image', 'Изображение')], default='notes', help_text='Тип материала: теория, конспект, Miro доска, документ и т.д.', max_length=20, verbose_name='тип материала'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='title',
            field=models.CharField(help_text='Название материала', max_length=255, verbose_name='название'),
        ),
        migrations.AddIndex(
            model_name='lessonmaterial',
            index=models.Index(fields=['material_type', 'uploaded_at'], name='schedule_le_materia_e371e1_idx'),
        ),
    ]
