# Generated by Django 5.2.8 on 2026-01-13 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_add_miro_fields_to_lesson_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiroUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Токен доступа Miro API', max_length=500, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, help_text='Токен для обновления access token', max_length=500, verbose_name='refresh token')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='тип токена')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Когда истекает access token', null=True, verbose_name='истекает')),
                ('miro_user_id', models.CharField(blank=True, help_text='ID пользователя в Miro', max_length=100, verbose_name='Miro User ID')),
                ('miro_team_id', models.CharField(blank=True, help_text='ID команды в Miro', max_length=100, verbose_name='Miro Team ID')),
                ('scopes', models.TextField(blank=True, help_text='Разрешения токена через пробел', verbose_name='scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='miro_token', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Miro токен пользователя',
                'verbose_name_plural': 'Miro токены пользователей',
            },
        ),
    ]
