# Generated by Django 5.2.8 on 2026-01-14 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_add_miro_user_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmaterial',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='material_access', to=settings.AUTH_USER_MODEL, verbose_name='доступные студенты'),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='visibility',
            field=models.CharField(choices=[('lesson_group', 'Только группа урока'), ('all_teacher_groups', 'Все группы преподавателя'), ('custom_groups', 'Выбранные группы'), ('custom_students', 'Выбранные ученики')], default='lesson_group', help_text='Кому доступен материал', max_length=32, verbose_name='видимость'),
        ),
    ]
