# Generated by Django 4.2.26 on 2026-01-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_add_allowed_students_to_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, default='', help_text='ID события в Google Calendar (для обновления/удаления)', max_length=255, verbose_name='ID события Google Calendar'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='google_meet_link',
            field=models.URLField(blank=True, default='', help_text='Ссылка на Google Meet для этого урока', max_length=500, verbose_name='ссылка Google Meet'),
        ),
    ]
