# Generated by Django 5.2.8 on 2026-01-15 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_add_google_meet_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonJoinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet')], help_text='Через какую платформу подключался', max_length=20, verbose_name='платформа')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, help_text='Когда ученик нажал кнопку Присоединиться', verbose_name='время клика')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_logs', to='schedule.lesson', verbose_name='урок')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_join_logs', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'лог подключения к уроку',
                'verbose_name_plural': 'логи подключений к урокам',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['lesson', 'student'], name='schedule_le_lesson__9b4b68_idx'), models.Index(fields=['clicked_at'], name='schedule_le_clicked_53b3eb_idx')],
            },
        ),
    ]
