# Generated by Django 5.2.8 on 2026-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_add_lesson_join_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID чата/группы в Telegram для отправки уведомлений (бот должен быть добавлен в группу)', max_length=50, verbose_name='Chat ID Telegram-группы'),
        ),
    ]
