# Generated by Django 5.2.8 on 2026-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_group_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecording',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='ссылка для скачивания'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='play_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='ссылка для просмотра'),
        ),
    ]
