# Generated by Django 5.2.8 on 2026-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_alter_lessonrecording_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Когда учитель завершил урок (нажал кнопку "Закончить" или meeting.ended от Zoom)', null=True, verbose_name='время завершения'),
        ),
    ]
