# Generated by Django 4.2.26 on 2026-02-01 08:24
# NOTE: This migration is a no-op because 0031_add_soft_delete_to_recording
# already adds the same fields. Both exist to maintain compatibility with
# production migration graph (0032_merge merges both leaf nodes).

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0030_add_ended_at_to_lesson'),
    ]

    operations = [
        # No-op: fields already added by 0031_add_soft_delete_to_recording
    ]
