# Generated by Django 5.2.8 on 2026-02-01 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_add_ended_at_to_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecording',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Когда запись была помечена как удалённая', null=True, verbose_name='дата удаления'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Кто инициировал удаление (для аудита)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_recordings', to=settings.AUTH_USER_MODEL, verbose_name='удалено пользователем'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', help_text='Опциональная причина удаления для аудита', max_length=255, verbose_name='причина удаления'),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete флаг. Удалённые записи не показываются в UI.', verbose_name='удалено'),
        ),
    ]
