# Generated by Django 4.2.26 on 2026-02-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_add_soft_delete_to_recording'),
        ('schedule', '0031_lessonrecording_deleted_at_and_more'),
    ]

    operations = [
    ]
