# Generated by Django 5.2.8 on 2026-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_fix_gdrive_file_id_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecording',
            name='archive_key',
            field=models.CharField(blank=True, help_text='ID файла в Google Drive или путь в S3/Azure', max_length=500, verbose_name='ключ в хранилище'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Уникальный ID файла в Google Drive для прямого доступа', max_length=100, verbose_name='Google Drive File ID'),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, help_text='ID папки в Google Drive где хранится запись', max_length=100, verbose_name='Google Drive Folder ID'),
        ),
    ]
