# Generated by Django 4.2.26 on 2026-03-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_alter_lessonrecording_archive_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Уникальный код для присоединения учеников к группе', max_length=8, null=True, unique=True, verbose_name='код приглашения'),
        ),
    ]
