# Generated by Django 5.2.11 on 2026-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auditlog_tenant_group_tenant_lesson_tenant_and_more'),
        ('schedule', '0034_add_school_fk_to_group'),
    ]

    operations = [
    ]
