"""
Django settings for teaching_panel project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate new key with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-your-secret-key-change-this-in-production')

# Warn if using default SECRET_KEY
if SECRET_KEY == 'django-insecure-your-secret-key-change-this-in-production':
    import warnings
    warnings.warn(
        "WARNING: Using default SECRET_KEY! Generate a new one for production!",
        RuntimeWarning
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')

# Отключаем проверку тестовых ключей reCAPTCHA для разработки
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_recaptcha',
    'core',
    'accounts',
    'schedule',
    'homework',
    'analytics',
    'zoom_pool',
    'support',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RequestMetricsMiddleware',  # Метрики запросов
]

ROOT_URLCONF = 'teaching_panel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Глобальная директория templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teaching_panel.wsgi.application'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Support for DATABASE_URL (production) or default SQLite (development)
try:
    import dj_database_url
    HAS_DJ_DATABASE_URL = True
except ImportError:
    HAS_DJ_DATABASE_URL = False

if os.environ.get('DATABASE_URL') and HAS_DJ_DATABASE_URL:
    # Production: Use PostgreSQL/MySQL via DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Cache Configuration
# Production: Use Redis for caching
# Development: Use local memory cache
if os.environ.get('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'teaching_panel',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    # Development fallback: local memory
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'teaching-panel-cache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for development
_CORS_DEFAULTS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]
# Include server host/IP for remote access (React build served on :3000 or proxied via Nginx)
_SERVER_HOST = os.environ.get('SERVER_HOST', '72.56.81.163')
_CORS_DEFAULTS.append(f"http://{_SERVER_HOST}:3000")
_CORS_DEFAULTS.append(f"http://{_SERVER_HOST}")

# Allow override / extension via env var CORS_EXTRA (comma-separated)
_CORS_EXTRA = [h for h in os.environ.get('CORS_EXTRA', '').split(',') if h]
CORS_ALLOWED_ORIGINS = _CORS_DEFAULTS + _CORS_EXTRA

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Increased from 10 for better UX
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '3000/hour',  # Increased for 1000 teachers + 3000 students
        'anon': '200/hour',     # Increased for mobile login attempts
        'login': '50/hour',     # Specific rate for login endpoint (per IP)
        'submissions': '100/hour',  # Specific rate for homework submissions
        'grading': '500/hour',      # Higher rate for teacher grading
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # Connection pooling for better performance
    'NUM_PROXIES': 1,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.CustomTokenObtainPairSerializer',
}

# Zoom API settings (Server-to-Server OAuth)
ZOOM_ACCOUNT_ID = os.environ.get('ZOOM_ACCOUNT_ID', '6w5GrnCgSgaHwMFFbhmlKw')
ZOOM_CLIENT_ID = os.environ.get('ZOOM_CLIENT_ID', 'vNl9EzZTy6h2UifsGVERg')
ZOOM_CLIENT_SECRET = os.environ.get('ZOOM_CLIENT_SECRET', 'jqMJb4R3UgOQ1Q2FEHtkv6Tkz3CxNX87')
ZOOM_WEBHOOK_SECRET_TOKEN = os.environ.get('ZOOM_WEBHOOK_SECRET_TOKEN', '2ocO-3htS8Sl1tVpEtZ2_A')

# Legacy JWT settings (deprecated by Zoom, but kept for backwards compatibility)
ZOOM_API_KEY = os.environ.get('ZOOM_API_KEY', '')
ZOOM_API_SECRET = os.environ.get('ZOOM_API_SECRET', '')

# Google Drive API settings (OAuth2)
GDRIVE_TOKEN_FILE = os.environ.get('GDRIVE_TOKEN_FILE', os.path.join(BASE_DIR, 'gdrive_token.json'))
GDRIVE_RECORDINGS_FOLDER_ID = os.environ.get('GDRIVE_RECORDINGS_FOLDER_ID', '')  # ID корневой папки в Google Drive

# Video compression settings
VIDEO_COMPRESSION_ENABLED = os.environ.get('VIDEO_COMPRESSION_ENABLED', '1') == '1'
VIDEO_MAX_RESOLUTION = os.environ.get('VIDEO_MAX_RESOLUTION', '1280:720')  # 720p
VIDEO_CRF = int(os.environ.get('VIDEO_CRF', '23'))  # 18-28, чем ниже = лучше качество
VIDEO_PRESET = os.environ.get('VIDEO_PRESET', 'medium')  # ultrafast/fast/medium/slow
AUDIO_BITRATE = os.environ.get('AUDIO_BITRATE', '128k')

# Authentication settings
LOGIN_URL = '/api/jwt/login/'  # SPA login, не Django admin
LOGIN_REDIRECT_URL = 'schedule:teacher_schedule'  # По умолчанию
LOGOUT_REDIRECT_URL = 'accounts:role_selection'

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 минут максимум на задачу

# Optional in-memory fallback for development when Redis not available.
# Enable by setting USE_IN_MEMORY_CELERY=1 in environment.
if os.environ.get('USE_IN_MEMORY_CELERY') == '1':
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'
    # Solo pool forced below on Windows; memory transport only supports limited concurrency.

# Windows-specific: use solo pool instead of prefork to avoid permission errors
import sys
if sys.platform == 'win32':
    CELERY_WORKER_POOL = 'solo'

# Celery Beat расписание
CELERY_BEAT_SCHEDULE = {
    'release-stuck-zoom-accounts': {
        'task': 'schedule.tasks.release_stuck_zoom_accounts',
        'schedule': 600.0,  # каждые 10 минут
    },
    'schedule-lesson-reminders': {
        'task': 'schedule.tasks.schedule_upcoming_lesson_reminders',
        'schedule': 300.0,  # каждые 5 минут
    },
    'check-expiring-subscriptions': {
        'task': 'accounts.tasks.check_expiring_subscriptions',
        'schedule': 21600.0,  # каждые 6 часов
    },
    'process-expired-subscriptions': {
        'task': 'accounts.tasks.process_expired_subscriptions',
        'schedule': 3600.0,  # ежечасно обновляем статусы
    },
    'cleanup-old-recordings': {
        'task': 'schedule.tasks.cleanup_old_recordings',
        'schedule': 86400.0,  # каждые 24 часа (03:00 UTC)
    },
}

# Azure Cosmos DB integration (feature-flagged)
COSMOS_DB_ENABLED = os.environ.get('COSMOS_DB_ENABLED', '0') == '1'
COSMOS_DB_URL = os.environ.get('COSMOS_DB_URL', 'https://localhost:8081/')  # Emulator default
COSMOS_DB_KEY = os.environ.get('COSMOS_DB_KEY', os.environ.get('COSMOS_DB_MASTER_KEY', ''))
COSMOS_DB_DATABASE = os.environ.get('COSMOS_DB_DATABASE', 'teaching_panel')

# Container / partition key definitions (hierarchical keys where appropriate)
COSMOS_DB_CONTAINERS = {
    'users': {
        'partition_key': '/userId',
    },
    'groups': {
        'partition_key': '/teacherId',  # choose teacherId as top-level for targeting queries per teacher
    },
    'lessons': {
        'partition_key': '/groupId',  # For HPK: can migrate to ['/groupId', '/lessonDate'] for large groups
        'hierarchical_partition_key': False,  # Set to True after migration
    },
    'homeworkAssignments': {
        'partition_key': '/groupId',
    },
    'homeworkSubmissions': {
        'partition_key': '/assignmentId',
    },
    'attendance': {
        'partition_key': '/lessonId',
    },
    'zoomAccounts': {
        'partition_key': '/zoomAccountId',
    },
    'analyticsEvents': {
        'partition_key': '/eventDate',  # YYYY-MM-DD for time-series sharding
        'ttl': 2592000,  # 30 days TTL for analytics events (auto-deletion)
        'description': 'Analytics events: lesson_started, homework_submitted, attendance_marked, etc.'
    },
}

# When disabled we avoid importing azure-cosmos in code paths.

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
# Для разработки используем console backend (выводит в терминал)
# Для production настройте SMTP сервер

# EMAIL_BACKEND для разработки - выводит письма в консоль
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# Настройки SMTP для production (Gmail пример):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Настройки SMTP для production (Yandex пример):
# EMAIL_HOST = 'smtp.yandex.ru'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# От кого письма
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@teachingpanel.com')

# URL фронтенда (для ссылок в письмах)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# =============================================================================
# GOOGLE RECAPTCHA V3 CONFIGURATION
# =============================================================================
# Регистрация: https://www.google.com/recaptcha/admin/create
# Выберите reCAPTCHA v3 для невидимой защиты
# Документация: https://developers.google.com/recaptcha/docs/v3

# Site Key (публичный ключ) - используется на фронтенде
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')  # Test key

# Secret Key (приватный ключ) - используется на бэкенде
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')  # Test key

# Минимальный score для reCAPTCHA v3 (0.0 - бот, 1.0 - человек)
RECAPTCHA_REQUIRED_SCORE = float(os.environ.get('RECAPTCHA_REQUIRED_SCORE', '0.5'))

# Использовать reCAPTCHA только если ключи настроены (не тестовые)
RECAPTCHA_ENABLED = os.environ.get('RECAPTCHA_ENABLED', 'false').lower() == 'true'

# Warn if using test keys in production
if not DEBUG and RECAPTCHA_PUBLIC_KEY == '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI':
    import warnings
    warnings.warn(
        "WARNING: Using reCAPTCHA test keys in production! Get real keys from https://www.google.com/recaptcha/admin",
        RuntimeWarning
    )

# =============================================================================
# SMS.RU CONFIGURATION
# =============================================================================
# Для настройки зарегистрируйтесь на https://sms.ru/
# Получите API ID в личном кабинете: https://sms.ru/api
# ВАЖНО: Храните API ID в переменных окружения, не коммитьте в git!

SMSRU_API_ID = os.environ.get('SMSRU_API_ID', '')
SMSRU_FROM_NAME = os.environ.get('SMSRU_FROM_NAME', 'Teaching Panel')

# Стоимость SMS: от 1.15 руб за SMS по России
# Регистрация: 2 минуты, пополнение: от 100 руб
# Документация API: https://sms.ru/api/send


# =============================================================================
# TELEGRAM BOT CONFIGURATION
# =============================================================================
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_USERNAME = os.environ.get('TELEGRAM_BOT_USERNAME', '')
TELEGRAM_BOT_WEBHOOK_SECRET = os.environ.get(
    'TELEGRAM_BOT_WEBHOOK_SECRET',
    TELEGRAM_BOT_TOKEN,
)


# =============================================================================
# PRODUCTION SECURITY SETTINGS
# =============================================================================
# Enable these settings in production by setting environment variables

# HTTPS/SSL Redirect
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 'yes')

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() in ('true', '1', 'yes')
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False').lower() in ('true', '1', 'yes')

# Secure cookies (enable in production with HTTPS)
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
SESSION_COOKIE_HTTPONLY = True  # Always True - prevents JavaScript access
CSRF_COOKIE_HTTPONLY = True

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# CSRF Trusted Origins (add your production domain)
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Warn if running in production mode without proper security
if not DEBUG:
    if not SECURE_SSL_REDIRECT:
        import warnings
        warnings.warn("WARNING: Running in production without HTTPS redirect! Set SECURE_SSL_REDIRECT=True", RuntimeWarning)
    if not SESSION_COOKIE_SECURE:
        import warnings
        warnings.warn("WARNING: Running in production without secure cookies! Set SESSION_COOKIE_SECURE=True", RuntimeWarning)

# =============================================================================
# SENTRY CONFIGURATION (Error Monitoring)
# =============================================================================
# Sentry для мониторинга ошибок в production
# Регистрация: https://sentry.io/
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.celery import CeleryIntegration
        from sentry_sdk.integrations.redis import RedisIntegration
        
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                CeleryIntegration(),
                RedisIntegration(),
            ],
            # Процент трассировки производительности
            traces_sample_rate=0.1 if not DEBUG else 0.0,
            # Процент отправки ошибок (1.0 = все)
            sample_rate=1.0,
            # Окружение
            environment='development' if DEBUG else 'production',
            # Release version (можно брать из git или CI/CD)
            release=os.environ.get('GIT_COMMIT', 'unknown'),
            # Отправлять PII (личные данные)?
            send_default_pii=False,
            # Максимум breadcrumbs (цепочка событий перед ошибкой)
            max_breadcrumbs=50,
        )
    except ImportError:
        import warnings
        warnings.warn(
            "Sentry SDK not installed. Install with: pip install sentry-sdk",
            RuntimeWarning
        )

# =============================================================================
# YOOKASSA PAYMENT SETTINGS
# =============================================================================
YOOKASSA_ACCOUNT_ID = os.environ.get('YOOKASSA_ACCOUNT_ID', '')
YOOKASSA_SECRET_KEY = os.environ.get('YOOKASSA_SECRET_KEY', '')
YOOKASSA_WEBHOOK_SECRET = os.environ.get('YOOKASSA_WEBHOOK_SECRET', '')

# Frontend URL для return_url после оплаты
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': os.environ.get('DJANGO_CONSOLE_LOG_LEVEL', 'INFO'),
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if os.environ.get('SQL_DEBUG') == '1' else 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_ROOT_LOG_LEVEL', 'INFO'),
    },
}
