"""
Django settings for teaching_panel project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab
from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# Try to load from project root first, then from BASE_DIR
for env_path in [
    Path(__file__).resolve().parent.parent.parent / '.env',  # Project root
    os.path.join(BASE_DIR, '.env'),  # teaching_panel/.env
]:
    if os.path.exists(env_path):
        load_dotenv(env_path)
        break

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate new key with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get('SECRET_KEY')

# CRITICAL: SECRET_KEY is required - no fallback for security
if not SECRET_KEY:
    if os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes'):
        # Only allow insecure key in explicit DEBUG mode for local development
        SECRET_KEY = 'django-insecure-dev-only-key-not-for-production'
        import warnings
        warnings.warn(
            "WARNING: Using insecure development SECRET_KEY! Set SECRET_KEY env var for production!",
            RuntimeWarning
        )
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "CRITICAL: SECRET_KEY environment variable is required in production! "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for security - explicitly set DEBUG=True for development
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS - configure via environment variable in production
# For development: ALLOWED_HOSTS='localhost,127.0.0.1'
# For production: ALLOWED_HOSTS='yourdomain.com,api.yourdomain.com'
_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
elif DEBUG:
    # Only allow localhost in development mode
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    # Production with no ALLOWED_HOSTS set - fail safely
    ALLOWED_HOSTS = []
    import warnings
    warnings.warn(
        "CRITICAL: No ALLOWED_HOSTS configured for production! Set ALLOWED_HOSTS environment variable.",
        RuntimeWarning
    )

# Отключаем проверку тестовых ключей reCAPTCHA для разработки
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_recaptcha',
    'core',
    'accounts',
    'schedule',
    'homework',
    'analytics',
    'zoom_pool',
    'support',
    'integrations',  # Third-party platform integrations (Google Meet, etc.)
    'bot',  # Telegram bot command center
    'market',  # Digital products marketplace (Zoom accounts, etc.)
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RequestMetricsMiddleware',  # Метрики запросов
    'accounts.bot_protection.BotProtectionMiddleware',  # Защита от ботов по fingerprint
]

ROOT_URLCONF = 'teaching_panel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Глобальная директория templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teaching_panel.wsgi.application'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Support for DATABASE_URL (production) or default SQLite (development)
try:
    import dj_database_url
    HAS_DJ_DATABASE_URL = True
except ImportError:
    HAS_DJ_DATABASE_URL = False

if os.environ.get('DATABASE_URL') and HAS_DJ_DATABASE_URL:
    # Production: Use PostgreSQL/MySQL via DATABASE_URL
    # NOTE: conn_max_age=0 is intentional for Celery workers (prevents stale connections)
    # Gunicorn with gthread can use persistent connections, but Celery should not
    _is_celery_worker = 'celery' in os.environ.get('CELERY_LOADER', '').lower() or \
                        any('celery' in arg.lower() for arg in os.sys.argv)
    _conn_max_age = 0 if _is_celery_worker else 60  # 1 minute for web, 0 for Celery
    
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=_conn_max_age,
            conn_health_checks=True,
        )
    }
    
    # Add PostgreSQL-specific options for connection stability
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,  # 10 seconds to establish connection
        'options': '-c statement_timeout=30000',  # 30 seconds max query time
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Cache Configuration
# Production: Use Redis for caching (django-redis)
# Development: Use local memory cache
if os.environ.get('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'tp',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    # Development fallback: local memory
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'teaching-panel-cache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings for large video files (up to 10GB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 * 1024  # 10GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 * 1024  # 10GB

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings for development
_CORS_DEFAULTS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]
# Include server host/IP for remote access (React build served on :3000 or proxied via Nginx)
_SERVER_HOST = os.environ.get('SERVER_HOST', '72.56.81.163')
_CORS_DEFAULTS.append(f"http://{_SERVER_HOST}:3000")
_CORS_DEFAULTS.append(f"http://{_SERVER_HOST}")

# Allow override / extension via env var CORS_EXTRA (comma-separated)
_CORS_EXTRA = [h for h in os.environ.get('CORS_EXTRA', '').split(',') if h]
CORS_ALLOWED_ORIGINS = _CORS_DEFAULTS + _CORS_EXTRA

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Increased from 10 for better UX
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '5000/hour',  # Increased for 1000 teachers + 3000 students
        'anon': '500/hour',     # Increased for mobile login attempts
        'login': '300/hour',     # Relaxed: was 50, too aggressive
        'submissions': '200/hour',  # Specific rate for homework submissions
        'grading': '1000/hour',      # Higher rate for teacher grading
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # Connection pooling for better performance
    'NUM_PROXIES': 1,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=12),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.CustomTokenObtainPairSerializer',
}

# Zoom API settings (Server-to-Server OAuth)
# CRITICAL: Never hardcode credentials! Use environment variables.
ZOOM_ACCOUNT_ID = os.environ.get('ZOOM_ACCOUNT_ID', '')
ZOOM_CLIENT_ID = os.environ.get('ZOOM_CLIENT_ID', '')
ZOOM_CLIENT_SECRET = os.environ.get('ZOOM_CLIENT_SECRET', '')
ZOOM_WEBHOOK_SECRET_TOKEN = os.environ.get('ZOOM_WEBHOOK_SECRET_TOKEN', '')

# Warn if Zoom credentials not configured
if not ZOOM_ACCOUNT_ID or not ZOOM_CLIENT_ID or not ZOOM_CLIENT_SECRET:
    import warnings
    warnings.warn(
        "WARNING: Zoom API credentials not configured! Set ZOOM_ACCOUNT_ID, ZOOM_CLIENT_ID, ZOOM_CLIENT_SECRET environment variables.",
        RuntimeWarning
    )

# Legacy JWT settings (deprecated by Zoom, but kept for backwards compatibility)
ZOOM_API_KEY = os.environ.get('ZOOM_API_KEY', '')
ZOOM_API_SECRET = os.environ.get('ZOOM_API_SECRET', '')

# Google Drive API settings (OAuth2)
GDRIVE_TOKEN_FILE = os.environ.get('GDRIVE_TOKEN_FILE', os.path.join(BASE_DIR, 'gdrive_token.json'))
GDRIVE_ROOT_FOLDER_ID = os.environ.get('GDRIVE_ROOT_FOLDER_ID', '')  # ID корневой папки Teaching Panel
GDRIVE_RECORDINGS_FOLDER_ID = os.environ.get('GDRIVE_RECORDINGS_FOLDER_ID', '')  # Записи уроков
GDRIVE_HOMEWORK_FOLDER_ID = os.environ.get('GDRIVE_HOMEWORK_FOLDER_ID', '')  # Домашние задания
GDRIVE_MATERIALS_FOLDER_ID = os.environ.get('GDRIVE_MATERIALS_FOLDER_ID', '')  # Материалы уроков
GDRIVE_ATTACHMENTS_FOLDER_ID = os.environ.get('GDRIVE_ATTACHMENTS_FOLDER_ID', '')  # Вложения

# Storage backends
USE_GDRIVE_STORAGE = os.environ.get('USE_GDRIVE_STORAGE', '0') == '1'  # Включить хранение на Google Drive

# =============================================================================
# Google Meet Integration (Feature-flagged)
# =============================================================================
# Enable Google Meet as alternative video platform for lessons
# Set GOOGLE_MEET_ENABLED=1 to enable the feature
GOOGLE_MEET_ENABLED = os.environ.get('GOOGLE_MEET_ENABLED', '0') == '1'

# Google OAuth2 credentials for Meet integration (Calendar API)
# Create OAuth 2.0 Client ID at https://console.cloud.google.com/apis/credentials
# Required scopes: https://www.googleapis.com/auth/calendar.events
GOOGLE_MEET_CLIENT_ID = os.environ.get('GOOGLE_MEET_CLIENT_ID', '')
GOOGLE_MEET_CLIENT_SECRET = os.environ.get('GOOGLE_MEET_CLIENT_SECRET', '')
GOOGLE_MEET_REDIRECT_URI = os.environ.get(
    'GOOGLE_MEET_REDIRECT_URI',
    'https://lectiospace.ru/api/integrations/google-meet/callback/'
)

# Video compression settings
VIDEO_COMPRESSION_ENABLED = os.environ.get('VIDEO_COMPRESSION_ENABLED', '1') == '1'
VIDEO_MAX_RESOLUTION = os.environ.get('VIDEO_MAX_RESOLUTION', '1280:720')  # 720p
VIDEO_CRF = int(os.environ.get('VIDEO_CRF', '23'))  # 18-28, чем ниже = лучше качество
VIDEO_PRESET = os.environ.get('VIDEO_PRESET', 'medium')  # ultrafast/fast/medium/slow
AUDIO_BITRATE = os.environ.get('AUDIO_BITRATE', '128k')

# Zoom recording cleanup after upload to Google Drive
ZOOM_DELETE_AFTER_UPLOAD = os.environ.get('ZOOM_DELETE_AFTER_UPLOAD', '1') == '1'

# Authentication settings
LOGIN_URL = '/api/jwt/login/'  # SPA login, не Django admin
LOGIN_REDIRECT_URL = 'schedule:teacher_schedule'  # По умолчанию
LOGOUT_REDIRECT_URL = 'accounts:role_selection'

# =============================================================================
# CELERY CONFIGURATION (Production-Grade)
# =============================================================================
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True

# =============================================================================
# PRODUCTION SAFETY: acks_late + reject_on_worker_lost
# Task won't be acknowledged until AFTER completion
# If worker crashes, task goes back to queue
# =============================================================================
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# =============================================================================
# TASK QUEUES: Separate heavy and light tasks
# Heavy tasks (video processing) don't block emails/notifications
# =============================================================================
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_QUEUES = (
    Queue('default', routing_key='default'),
    Queue('heavy', routing_key='heavy'),  # Video processing, GDrive uploads
    Queue('notifications', routing_key='notifications'),  # Emails, Telegram
    Queue('periodic', routing_key='periodic'),  # Scheduled tasks from beat
)

# Route tasks to appropriate queues
CELERY_TASK_ROUTES = {
    # Heavy tasks → heavy queue
    'schedule.tasks.process_zoom_recording': {'queue': 'heavy'},
    'schedule.tasks.process_zoom_recording_bundle': {'queue': 'heavy'},
    'schedule.tasks.upload_recording_to_gdrive_robust': {'queue': 'heavy'},
    'schedule.tasks.archive_zoom_recordings': {'queue': 'heavy'},
    'accounts.tasks.sync_teacher_storage_usage': {'queue': 'heavy'},
    
    # Notification tasks → notifications queue  
    'schedule.tasks.send_lesson_reminder': {'queue': 'notifications'},
    'schedule.tasks.send_recurring_lesson_reminders': {'queue': 'notifications'},
    'accounts.tasks.check_expiring_subscriptions': {'queue': 'notifications'},
    'accounts.tasks.send_student_absence_warnings': {'queue': 'notifications'},
    'accounts.tasks.send_student_inactivity_nudges': {'queue': 'notifications'},
    'accounts.tasks.send_top_rating_notifications': {'queue': 'notifications'},
    'bot.tasks.process_scheduled_messages': {'queue': 'notifications'},
    
    # Periodic tasks → periodic queue
    'schedule.tasks.warmup_zoom_oauth_tokens': {'queue': 'periodic'},
    'schedule.tasks.release_stuck_zoom_accounts': {'queue': 'periodic'},
    'accounts.tasks.process_expired_subscriptions': {'queue': 'periodic'},
}

# =============================================================================
# RETRY DEFAULTS: Exponential backoff for transient failures
# =============================================================================
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute initial delay
CELERY_TASK_MAX_RETRIES = 3  # Default max retries

# =============================================================================
# TIME LIMITS: Prevent tasks from running forever and blocking workers
# =============================================================================
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes soft limit (raises SoftTimeLimitExceeded)
CELERY_TASK_TIME_LIMIT = 600       # 10 minutes hard limit (kills task with SIGKILL)

# =============================================================================
# PREFETCH: Limit tasks per worker to improve fairness
# =============================================================================
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only prefetch 1 task per worker

# =============================================================================
# MEMORY OPTIMIZATION: Prevent memory leaks in long-running workers
# Critical for 2GB RAM servers with multiple Python processes
# =============================================================================
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restart worker after 50 tasks to free memory
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 150000  # 150MB limit per worker, then restart

# =============================================================================
# REDIS CONNECTION: Prevent stale connections
# =============================================================================
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,  # 1 hour (must be > longest task)
    'socket_timeout': 30,
    'socket_connect_timeout': 30,
}
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'socket_timeout': 30,
    'socket_connect_timeout': 30,
}

# Explicit task module imports - ensures all tasks are registered on worker startup
# This fixes the KeyError issue where tasks weren't discovered
CELERY_IMPORTS = (
    'accounts.tasks',
    'schedule.tasks',
    'homework.tasks',
    'bot.tasks',
    'teaching_panel.telegram_logging',  # Telegram error alerting task
)

# Optional in-memory fallback for development when Redis not available.
# Enable by setting USE_IN_MEMORY_CELERY=1 in environment.
if os.environ.get('USE_IN_MEMORY_CELERY') == '1':
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'
    # Solo pool forced below on Windows; memory transport only supports limited concurrency.

# Windows-specific: use solo pool instead of prefork to avoid permission errors
import sys
if sys.platform == 'win32':
    CELERY_WORKER_POOL = 'solo'

# Celery Beat расписание
# OPTIMIZED 2026-02-02: Снижена частота задач для экономии памяти на 2GB сервере
CELERY_BEAT_SCHEDULE = {
    'warmup-zoom-oauth-tokens': {
        'task': 'schedule.tasks.warmup_zoom_oauth_tokens',
        'schedule': 3300.0,  # каждые 55 минут - держим токены горячими
    },
    'release-stuck-zoom-accounts': {
        'task': 'schedule.tasks.release_stuck_zoom_accounts',
        'schedule': 900.0,  # каждые 15 минут (было 10)
    },
    'schedule-lesson-reminders': {
        'task': 'schedule.tasks.schedule_upcoming_lesson_reminders',
        'schedule': 600.0,  # каждые 10 минут (было 5)
    },
    'send-recurring-lesson-reminders': {
        'task': 'schedule.tasks.send_recurring_lesson_reminders',
        'schedule': 120.0,  # каждые 2 минуты (было 60 сек)
    },
    'check-expiring-subscriptions': {
        'task': 'accounts.tasks.check_expiring_subscriptions',
        'schedule': 21600.0,  # каждые 6 часов
    },
    'process-expired-subscriptions': {
        'task': 'accounts.tasks.process_expired_subscriptions',
        'schedule': 3600.0,  # ежечасно обновляем статусы
    },
    'sync-teacher-storage-usage': {
        'task': 'accounts.tasks.sync_teacher_storage_usage',
        'schedule': 21600.0,  # каждые 6 часов (4 раза в день)
    },
    'cleanup-old-recordings': {
        'task': 'schedule.tasks.cleanup_old_recordings',
        'schedule': 86400.0,  # каждые 24 часа (03:00 UTC)
    },
    'check-consecutive-absences': {
        'task': 'accounts.tasks.check_consecutive_absences',
        'schedule': 86400.0,  # ежедневно (проверка пропусков)
    },
    # --- Analytics Notifications (Teacher) ---
    'check-performance-drops': {
        'task': 'accounts.tasks.check_performance_drops',
        'schedule': 86400.0,  # ежедневно
    },
    'check-group-health': {
        'task': 'accounts.tasks.check_group_health',
        'schedule': 604800.0,  # раз в неделю (7 дней)
    },
    'check-grading-backlog': {
        'task': 'accounts.tasks.check_grading_backlog',
        'schedule': 21600.0,  # каждые 6 часов
    },
    'check-inactive-students': {
        'task': 'accounts.tasks.check_inactive_students',
        'schedule': 86400.0,  # ежедневно
    },
    # --- Analytics Notifications (Student) ---
    'send-student-absence-warnings': {
        'task': 'accounts.tasks.send_student_absence_warnings',
        'schedule': 86400.0,  # ежедневно
    },
    'send-student-inactivity-nudges': {
        'task': 'accounts.tasks.send_student_inactivity_nudges',
        'schedule': 604800.0,  # раз в неделю
    },
    # --- Top Rating Notifications ---
    'send-monthly-top-rating': {
        'task': 'accounts.tasks.send_top_rating_notifications',
        'schedule': crontab(day_of_month='1', hour='10', minute='0'),  # 1 числа каждого месяца в 10:00
    },
    'send-season-top-rating': {
        'task': 'accounts.tasks.send_season_top_rating_notifications',
        'schedule': crontab(day_of_month='1', month_of_year='3,6,9,12', hour='11', minute='0'),  # 1 марта, июня, сентября, декабря в 11:00
    },
    # --- Subscription Auto-Renewals ---
    'process-auto-renewals': {
        'task': 'accounts.tasks.process_auto_renewals',
        'schedule': crontab(hour='9', minute='0'),  # ежедневно в 09:00
    },
    'process-zoom-addon-renewals': {
        'task': 'accounts.tasks.process_zoom_addon_renewals',
        'schedule': crontab(hour='9', minute='30'),  # ежедневно в 09:30
    },
    # --- Weekly Revenue Report ---
    'send-weekly-revenue-report': {
        'task': 'accounts.tasks.send_weekly_revenue_report_task',
        'schedule': crontab(day_of_week='monday', hour='10', minute='0'),  # каждый понедельник в 10:00
    },
    # --- Telegram Bot Tasks ---
    'process-scheduled-messages': {
        'task': 'bot.tasks.process_scheduled_messages',
        'schedule': 60.0,  # каждую минуту
    },
    'cleanup-redis-dialog-states': {
        'task': 'bot.tasks.cleanup_redis_dialog_states',
        'schedule': 259200.0,  # каждые 3 дня
    },
    'cleanup-old-broadcast-logs': {
        'task': 'bot.tasks.cleanup_old_broadcast_logs',
        'schedule': 604800.0,  # каждую неделю
    },
}

# Azure Cosmos DB integration (feature-flagged)
COSMOS_DB_ENABLED = os.environ.get('COSMOS_DB_ENABLED', '0') == '1'
COSMOS_DB_URL = os.environ.get('COSMOS_DB_URL', 'https://localhost:8081/')  # Emulator default
COSMOS_DB_KEY = os.environ.get('COSMOS_DB_KEY', os.environ.get('COSMOS_DB_MASTER_KEY', ''))
COSMOS_DB_DATABASE = os.environ.get('COSMOS_DB_DATABASE', 'teaching_panel')

# Container / partition key definitions (hierarchical keys where appropriate)
COSMOS_DB_CONTAINERS = {
    'users': {
        'partition_key': '/userId',
    },
    'groups': {
        'partition_key': '/teacherId',  # choose teacherId as top-level for targeting queries per teacher
    },
    'lessons': {
        'partition_key': '/groupId',  # For HPK: can migrate to ['/groupId', '/lessonDate'] for large groups
        'hierarchical_partition_key': False,  # Set to True after migration
    },
    'homeworkAssignments': {
        'partition_key': '/groupId',
    },
    'homeworkSubmissions': {
        'partition_key': '/assignmentId',
    },
    'attendance': {
        'partition_key': '/lessonId',
    },
    'zoomAccounts': {
        'partition_key': '/zoomAccountId',
    },
    'analyticsEvents': {
        'partition_key': '/eventDate',  # YYYY-MM-DD for time-series sharding
        'ttl': 2592000,  # 30 days TTL for analytics events (auto-deletion)
        'description': 'Analytics events: lesson_started, homework_submitted, attendance_marked, etc.'
    },
}

# When disabled we avoid importing azure-cosmos in code paths.

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
# Для разработки используем console backend (выводит в терминал)
# Для production настройте SMTP сервер

# EMAIL_BACKEND для разработки - выводит письма в консоль
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# Настройки SMTP для production (Gmail пример):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Настройки SMTP для production (Yandex пример):
# EMAIL_HOST = 'smtp.yandex.ru'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# От кого письма
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@teachingpanel.com')

# URL фронтенда (для ссылок в письмах)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# =============================================================================
# GOOGLE RECAPTCHA V3 CONFIGURATION
# =============================================================================
# Регистрация: https://www.google.com/recaptcha/admin/create
# Выберите reCAPTCHA v3 для невидимой защиты
# Документация: https://developers.google.com/recaptcha/docs/v3

# Site Key (публичный ключ) - используется на фронтенде
# SECURITY: No fallback to test keys - must be explicitly configured
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', '')

# Secret Key (приватный ключ) - используется на бэкенде
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', '')

# Минимальный score для reCAPTCHA v3 (0.0 - бот, 1.0 - человек)
RECAPTCHA_REQUIRED_SCORE = float(os.environ.get('RECAPTCHA_REQUIRED_SCORE', '0.5'))

# reCAPTCHA включается только если настроены реальные ключи
# Автоматически отключается если ключи не заданы
_recaptcha_keys_configured = bool(RECAPTCHA_PUBLIC_KEY and RECAPTCHA_PRIVATE_KEY)
RECAPTCHA_ENABLED = _recaptcha_keys_configured and os.environ.get('RECAPTCHA_ENABLED', 'false').lower() == 'true'

# Warn in production if reCAPTCHA not configured
if not DEBUG and not _recaptcha_keys_configured:
    import warnings
    warnings.warn(
        "WARNING: reCAPTCHA not configured. Set RECAPTCHA_PUBLIC_KEY and RECAPTCHA_PRIVATE_KEY for bot protection.",
        RuntimeWarning
    )

# Warn if using test keys in production
if not DEBUG and RECAPTCHA_PUBLIC_KEY == '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI':
    import warnings
    warnings.warn(
        "WARNING: Using reCAPTCHA test keys in production! Get real keys from https://www.google.com/recaptcha/admin",
        RuntimeWarning
    )

# =============================================================================
# SMS.RU CONFIGURATION
# =============================================================================
# Для настройки зарегистрируйтесь на https://sms.ru/
# Получите API ID в личном кабинете: https://sms.ru/api
# ВАЖНО: Храните API ID в переменных окружения, не коммитьте в git!

SMSRU_API_ID = os.environ.get('SMSRU_API_ID', '')
SMSRU_FROM_NAME = os.environ.get('SMSRU_FROM_NAME', 'Lectio Space')

# Стоимость SMS: от 1.15 руб за SMS по России
# Регистрация: 2 минуты, пополнение: от 100 руб
# Документация API: https://sms.ru/api/send


# =============================================================================
# TELEGRAM BOT CONFIGURATION
# =============================================================================
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_USERNAME = os.environ.get('TELEGRAM_BOT_USERNAME', '')
TELEGRAM_BOT_WEBHOOK_SECRET = os.environ.get(
    'TELEGRAM_BOT_WEBHOOK_SECRET',
    TELEGRAM_BOT_TOKEN,
)

# Отдельный бот для уведомлений о платежах
# Используется для отправки уведомлений админу о новых оплатах
TELEGRAM_PAYMENTS_BOT_TOKEN = os.environ.get('TELEGRAM_PAYMENTS_BOT_TOKEN', '')

# Admin chat ID for payment notifications
# Set this to your Telegram chat_id (get it from @userinfobot)
ADMIN_PAYMENT_TELEGRAM_CHAT_ID = os.environ.get('ADMIN_PAYMENT_TELEGRAM_CHAT_ID', '')

# Отдельный бот для уведомлений о заявках (регистрациях)
TELEGRAM_REQUESTS_BOT_TOKEN = os.environ.get('TELEGRAM_REQUESTS_BOT_TOKEN', '')

# Chat ID куда отправлять уведомления о заявках.
# Если не задан — уведомления будут отправлены всем staff с telegram_id (fallback).
TELEGRAM_REQUESTS_CHAT_ID = os.environ.get('TELEGRAM_REQUESTS_CHAT_ID', '')

# Бот/чат для процессных алертов (ошибки бизнес-флоу: оплаты/ДЗ/записи и т.д.)
# По умолчанию можно переиспользовать ERRORS_* если эти переменные проброшены в env сервиса.
PROCESS_ALERTS_BOT_TOKEN = os.environ.get('PROCESS_ALERTS_BOT_TOKEN', '') or os.environ.get('ERRORS_BOT_TOKEN', '')
PROCESS_ALERTS_CHAT_ID = os.environ.get('PROCESS_ALERTS_CHAT_ID', '') or os.environ.get('ERRORS_CHAT_ID', '')

# Бот/чат для Django 500 ошибок (используется в telegram_logging.py)
ERRORS_BOT_TOKEN = os.environ.get('ERRORS_BOT_TOKEN', '')
ERRORS_CHAT_ID = os.environ.get('ERRORS_CHAT_ID', '')


# =============================================================================
# PRODUCTION SECURITY SETTINGS
# =============================================================================
# Enable these settings in production by setting environment variables

# HTTPS/SSL Redirect
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 'yes')

# Trust X-Forwarded-Proto header from nginx (required when behind reverse proxy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Exempt healthcheck from SSL redirect (for internal monitoring)
SECURE_REDIRECT_EXEMPT = [r'^api/health/$']

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() in ('true', '1', 'yes')
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False').lower() in ('true', '1', 'yes')

# Secure cookies (enable in production with HTTPS)
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
SESSION_COOKIE_HTTPONLY = True  # Always True - prevents JavaScript access
CSRF_COOKIE_HTTPONLY = True

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# CSRF Trusted Origins (add your production domain)
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Warn if running in production mode without proper security
if not DEBUG:
    if not SECURE_SSL_REDIRECT:
        import warnings
        warnings.warn("WARNING: Running in production without HTTPS redirect! Set SECURE_SSL_REDIRECT=True", RuntimeWarning)
    if not SESSION_COOKIE_SECURE:
        import warnings
        warnings.warn("WARNING: Running in production without secure cookies! Set SESSION_COOKIE_SECURE=True", RuntimeWarning)

# =============================================================================
# SENTRY CONFIGURATION (Error Monitoring)
# =============================================================================
# Sentry для мониторинга ошибок в production
# Регистрация: https://sentry.io/
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.celery import CeleryIntegration
        from sentry_sdk.integrations.redis import RedisIntegration
        
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                CeleryIntegration(),
                RedisIntegration(),
            ],
            # Performance tracing может быть платным/шумным. По умолчанию отключено.
            # Включайте явно через env: SENTRY_TRACES_SAMPLE_RATE=0.1
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.0')) if not DEBUG else 0.0,
            # Процент отправки ошибок (1.0 = все)
            sample_rate=1.0,
            # Окружение
            environment='development' if DEBUG else 'production',
            # Release version (можно брать из git или CI/CD)
            release=os.environ.get('GIT_COMMIT', 'unknown'),
            # Отправлять PII (личные данные)?
            send_default_pii=False,
            # Максимум breadcrumbs (цепочка событий перед ошибкой)
            max_breadcrumbs=50,
        )
    except ImportError:
        import warnings
        warnings.warn(
            "Sentry SDK not installed. Install with: pip install sentry-sdk",
            RuntimeWarning
        )

# =============================================================================
# YOOKASSA PAYMENT SETTINGS
# =============================================================================
YOOKASSA_ACCOUNT_ID = os.environ.get('YOOKASSA_ACCOUNT_ID', '')
YOOKASSA_SECRET_KEY = os.environ.get('YOOKASSA_SECRET_KEY', '')
YOOKASSA_WEBHOOK_SECRET = os.environ.get('YOOKASSA_WEBHOOK_SECRET', '')

# =============================================================================
# T-BANK (ex-TINKOFF) PAYMENT SETTINGS
# =============================================================================
# TerminalKey (идентификатор терминала) - выдается при подключении эквайринга
# Docs: https://developer.tbank.ru/eacq/intro
TBANK_TERMINAL_KEY = os.environ.get('TBANK_TERMINAL_KEY', '')
# Password для подписи запросов (Token) - из личного кабинета
TBANK_PASSWORD = os.environ.get('TBANK_PASSWORD', '')
# Какой провайдер использовать по умолчанию: 'tbank' (YooKassa не используется)
DEFAULT_PAYMENT_PROVIDER = os.environ.get('DEFAULT_PAYMENT_PROVIDER', 'tbank')

# Frontend URL для return_url после оплаты
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')
# Site URL для webhook callbacks (может отличаться от FRONTEND_URL)
SITE_URL = os.environ.get('SITE_URL', os.environ.get('FRONTEND_URL', 'http://localhost:8000'))

# =============================================================================
# AI GRADING SETTINGS
# =============================================================================
# DeepSeek API (рекомендуется) - бесплатные кредиты при регистрации
# Получить ключ: https://platform.deepseek.com/
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')

# OpenAI API (альтернатива)
# Получить ключ: https://platform.openai.com/
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
# CRITICAL: Используем thread-safe handlers для предотвращения
# RuntimeError: reentrant call inside <_io.BufferedWriter>
# при одновременной записи из нескольких потоков gthread/gevent
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': os.environ.get('DJANGO_CONSOLE_LOG_LEVEL', 'INFO'),
            # Thread-safe handler для многопоточного Gunicorn
            'class': 'teaching_panel.safe_logging.ThreadSafeStreamHandler',
            'formatter': 'verbose',
        },
        'db_errors': {
            'level': os.environ.get('DJANGO_DB_ERRORS_LOG_LEVEL', 'ERROR'),
            'class': 'accounts.logging_handlers.DatabaseErrorLogHandler',
            'formatter': 'verbose',
        },
        'telegram': {
            'level': 'ERROR',
            'class': 'teaching_panel.telegram_logging.TelegramErrorHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'db_errors', 'telegram'],
            'level': 'ERROR',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'db_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if os.environ.get('SQL_DEBUG') == '1' else 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'db_errors'],
        'level': os.environ.get('DJANGO_ROOT_LOG_LEVEL', 'INFO'),
    },
}
