# Generated by Django 5.2.8 on 2025-11-14 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0007_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_points', models.IntegerField(default=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='schedule.group')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_points', to='schedule.lesson')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'контрольная точка',
                'verbose_name_plural': 'контрольные точки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ControlPointResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.controlpoint')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='control_point_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'результат контрольной точки',
                'verbose_name_plural': 'результаты контрольных точек',
                'unique_together': {('control_point', 'student')},
            },
        ),
    ]
