# Generated by Django 5.2.8 on 2025-12-26 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('schedule', '0018_lesson_title_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает генерации'), ('generating', 'Генерируется'), ('completed', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('total_submissions', models.IntegerField(default=0)),
                ('avg_score_percent', models.FloatField(blank=True, null=True)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('questions_needing_review', models.IntegerField(default=0)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='\n    {\n        "strengths": ["Сильная сторона 1", "Сильная сторона 2"],\n        "weaknesses": ["Слабая сторона 1", "Слабая сторона 2"],\n        "common_mistakes": [\n            {"topic": "Present Perfect", "frequency": 5, "examples": ["..."]},\n        ],\n        "recommendations": ["Рекомендация 1", "Рекомендация 2"],\n        "progress_trend": "improving|stable|declining",\n        "summary": "Краткое резюме о прогрессе студента..."\n    }\n    ')),
                ('ai_provider', models.CharField(default='deepseek', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='schedule.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI-отчет по студенту',
                'verbose_name_plural': 'AI-отчеты по студентам',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'teacher', 'period_start', 'period_end')},
            },
        ),
    ]
