# Generated by Django 5.2.11 on 2026-02-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0004_school_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='tenants.tenant', verbose_name='Тенант'),
        ),
    ]
