# Generated by Django 4.2.26 on 2025-12-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0018_lesson_title_optional'),
        ('analytics', '0002_add_student_ai_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBehaviorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает генерации'), ('generating', 'Генерируется'), ('completed', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('total_lessons', models.IntegerField(default=0, help_text='Всего занятий за период')),
                ('attended_lessons', models.IntegerField(default=0, help_text='Посещено занятий')),
                ('missed_lessons', models.IntegerField(default=0, help_text='Пропущено занятий')),
                ('late_arrivals', models.IntegerField(default=0, help_text='Опоздания на занятия')),
                ('attendance_rate', models.FloatField(blank=True, help_text='Процент посещаемости', null=True)),
                ('total_homework', models.IntegerField(default=0, help_text='Всего ДЗ за период')),
                ('submitted_on_time', models.IntegerField(default=0, help_text='Сдано вовремя')),
                ('submitted_late', models.IntegerField(default=0, help_text='Сдано с опозданием')),
                ('not_submitted', models.IntegerField(default=0, help_text='Не сдано')),
                ('homework_rate', models.FloatField(blank=True, help_text='Процент сданных ДЗ', null=True)),
                ('avg_score', models.FloatField(blank=True, help_text='Средний балл', null=True)),
                ('score_trend', models.CharField(blank=True, choices=[('improving', '📈 Улучшается'), ('stable', '➡️ Стабильно'), ('declining', '📉 Ухудшается')], max_length=20, null=True)),
                ('control_points_count', models.IntegerField(default=0, help_text='Контрольных точек')),
                ('control_points_avg', models.FloatField(blank=True, help_text='Средний балл контрольных', null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', '🟢 Низкий'), ('medium', '🟡 Средний'), ('high', '🔴 Высокий')], max_length=10, null=True)),
                ('reliability_score', models.IntegerField(blank=True, help_text='Балл надёжности 0-100', null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='\n    {\n        "profile_type": "responsible|needs_attention|at_risk",\n        "strengths": ["Регулярно посещает занятия", ...],\n        "concerns": ["Часто опаздывает", "Не сдаёт ДЗ вовремя", ...],\n        "patterns": [\n            {"type": "attendance", "description": "Пропускает занятия по понедельникам"},\n            {"type": "homework", "description": "Сдаёт ДЗ в последний момент"}\n        ],\n        "recommendations": [\n            {"priority": "high", "action": "Связаться с учеником по поводу пропусков"},\n            {"priority": "medium", "action": "Предложить записи пропущенных занятий"}\n        ],\n        "alerts": [\n            {"type": "warning", "message": "Пропустил 3 занятия подряд"}\n        ],\n        "predicted_completion_probability": 75,\n        "summary": "Краткое резюме о поведении ученика..."\n    }\n    ')),
                ('ai_provider', models.CharField(default='deepseek', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to='schedule.group')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_behavior_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поведенческий AI-отчёт',
                'verbose_name_plural': 'Поведенческие AI-отчёты',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'teacher', 'group', 'period_start', 'period_end')},
            },
        ),
    ]
