# Generated by Django 4.2.26 on 2026-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_student_behavior_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='controlpoint',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='controlpointresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
