# Generated by Django 5.2.8 on 2026-03-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_add_db_indexes'),
        ('knowledge_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Тема экзамена для карты знаний (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_points_analytics', to='knowledge_map.topic'),
        ),
    ]
