# Generated by Django 5.2.8 on 2026-02-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_add_db_indexes'),
        ('tenants', '0002_create_default_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_points', to='tenants.school'),
        ),
    ]
