# Generated by Django 5.2.11 on 2026-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_controlpoint_tenant'),
        ('analytics', '0005_add_school_fk_to_controlpoint'),
    ]

    operations = [
    ]
