# Generated by Django 4.2.26 on 2026-02-10 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_backfill_school_fk'),
        ('homework', '0023_add_ai_grading_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название: "ЕГЭ Информатика 2026"', max_length=255)),
                ('year', models.PositiveIntegerField(default=2026, help_text='Год экзамена (для привязки шкалы ФИПИ)', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2035)])),
                ('duration_minutes', models.PositiveIntegerField(default=235, help_text='Длительность экзамена в минутах')),
                ('total_primary_score', models.PositiveIntegerField(default=0, help_text='Максимальный первичный балл (сумма баллов всех заданий)')),
                ('score_scale', models.JSONField(blank=True, default=dict, help_text='Таблица перевода: {"первичный_балл": тестовый_балл, ...}')),
                ('grade_thresholds', models.JSONField(blank=True, default=dict, help_text='Пороги оценок: {"оценка": мин_тестовый_балл, ...}')),
                ('description', models.TextField(blank=True, default='', help_text='Описание / инструкции к экзамену')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли шаблон (неактивные скрыты в UI)')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли всем учителям платформы (иначе только автору)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Автор шаблона', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprints', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text='Школа (multi-tenant)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_blueprints', to='tenants.school')),
                ('subject', models.ForeignKey(help_text='Предмет (ЕГЭ Информатика, ОГЭ Математика...)', on_delete=django.db.models.deletion.PROTECT, related_name='exam_blueprints', to='knowledge_map.subject')),
            ],
            options={
                'verbose_name': 'Шаблон экзамена',
                'verbose_name_plural': 'Шаблоны экзаменов',
                'ordering': ['-year', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField(help_text='Номер задания в КИМ (к какому слоту относится)')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкое'), ('medium', 'Среднее'), ('hard', 'Сложное')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('fipi', 'ФИПИ (официальный банк)'), ('reshu_ege', 'Решу ЕГЭ / Решу ОГЭ'), ('author', 'Авторское задание'), ('textbook', 'Учебник'), ('olympiad', 'Олимпиадное'), ('other', 'Другой источник')], default='author', max_length=20)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Номер в банке ФИПИ / ссылка на источник', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Теги для фильтрации: ["рекурсия", "сортировка", ...]')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Сколько раз использовано в вариантах')),
                ('is_active', models.BooleanField(default=True, help_text='Активно (неактивные не выбираются при генерации)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(help_text='Шаблон экзамена', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='exam.examblueprint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_tasks', to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(help_text='Вопрос с текстом, config и вариантами ответа', on_delete=django.db.models.deletion.CASCADE, related_name='exam_task', to='homework.question')),
            ],
            options={
                'verbose_name': 'Задание банка',
                'verbose_name_plural': 'Задания банка',
                'ordering': ['task_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_number', models.PositiveIntegerField(default=1, help_text='Номер варианта')),
                ('title', models.CharField(blank=True, default='', help_text='Название варианта: "Вариант 1"', max_length=255)),
                ('is_manual', models.BooleanField(default=False, help_text='Собран вручную (True) или сгенерирован (False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='exam.examblueprint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variants', to=settings.AUTH_USER_MODEL)),
                ('homework', models.OneToOneField(blank=True, help_text='Связанное ДЗ (создаётся при назначении)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_variant', to='homework.homework')),
            ],
            options={
                'verbose_name': 'Вариант экзамена',
                'verbose_name_plural': 'Варианты экзаменов',
                'ordering': ['variant_number'],
                'unique_together': {('blueprint', 'variant_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='Когда ученик начал экзамен', null=True)),
                ('deadline_at', models.DateTimeField(blank=True, help_text='Дедлайн = started_at + duration_minutes', null=True)),
                ('auto_submitted', models.BooleanField(default=False, help_text='Сдан автоматически по таймеру')),
                ('primary_score', models.PositiveIntegerField(blank=True, null=True)),
                ('test_score', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=5)),
                ('task_scores', models.JSONField(blank=True, default=list)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('fullscreen_exits', models.PositiveIntegerField(default=0)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempt', to='homework.studentsubmission')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.examvariant')),
            ],
            options={
                'verbose_name': 'Попытка экзамена',
                'verbose_name_plural': 'Попытки экзаменов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamVariantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField(help_text='Номер задания в варианте')),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_usages', to='exam.examtask')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_tasks', to='exam.examvariant')),
            ],
            options={
                'verbose_name': 'Задание в варианте',
                'verbose_name_plural': 'Задания в вариантах',
                'ordering': ['task_number'],
                'unique_together': {('variant', 'task_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamTaskSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField(help_text='Номер задания в КИМ (1-27 и т.д.)')),
                ('title', models.CharField(blank=True, default='', help_text='Краткое описание типа задания: "Анализ информационных моделей"', max_length=255)),
                ('answer_type', models.CharField(choices=[('short_number', 'Краткий числовой ответ'), ('short_text', 'Краткий текстовый ответ'), ('digit_sequence', 'Последовательность цифр'), ('letter_sequence', 'Последовательность букв (АБВГД)'), ('decimal_number', 'Десятичная дробь'), ('number_range', 'Диапазон чисел (через дефис)'), ('multiple_numbers', 'Несколько чисел через пробел'), ('matching', 'Соответствие (таблица)'), ('ordered_sequence', 'Упорядоченная последовательность'), ('single_choice', 'Один вариант ответа'), ('multi_choice', 'Несколько вариантов ответа'), ('extended_text', 'Развёрнутый текстовый ответ'), ('essay', 'Сочинение / эссе'), ('math_solution', 'Математическое решение'), ('code_solution', 'Программный код (в редакторе)'), ('code_file', 'Файл с программой')], default='short_number', help_text='Формат ожидаемого ответа', max_length=30)),
                ('max_points', models.PositiveIntegerField(default=1, help_text='Максимальный балл за задание')),
                ('answer_config', models.JSONField(blank=True, default=dict, help_text='Параметры формата ответа (зависит от answer_type)')),
                ('description', models.TextField(blank=True, default='', help_text='Описание типа задания (видно учителю при создании банка)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (обычно = task_number)')),
                ('blueprint', models.ForeignKey(help_text='Шаблон экзамена', on_delete=django.db.models.deletion.CASCADE, related_name='task_slots', to='exam.examblueprint')),
                ('topic', models.ForeignKey(blank=True, help_text='Тема из карты знаний (для аналитики слабых мест)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_task_slots', to='knowledge_map.topic')),
            ],
            options={
                'verbose_name': 'Слот задания',
                'verbose_name_plural': 'Слоты заданий',
                'ordering': ['task_number'],
                'unique_together': {('blueprint', 'task_number')},
            },
        ),
        migrations.AddIndex(
            model_name='examtask',
            index=models.Index(fields=['blueprint', 'task_number'], name='exam_task_bp_num_idx'),
        ),
        migrations.AddIndex(
            model_name='examtask',
            index=models.Index(fields=['difficulty'], name='exam_task_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='examtask',
            index=models.Index(fields=['is_active'], name='exam_task_active_idx'),
        ),
        migrations.AddIndex(
            model_name='examblueprint',
            index=models.Index(fields=['subject', 'year'], name='exam_bp_subject_year_idx'),
        ),
        migrations.AddIndex(
            model_name='examblueprint',
            index=models.Index(fields=['is_active'], name='exam_bp_active_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['variant', 'started_at'], name='exam_att_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['deadline_at'], name='exam_att_deadline_idx'),
        ),
    ]
