# Generated by Django 5.2.8 on 2026-03-03 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0034_alter_lessonrecording_archive_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_preset', models.BooleanField(default=False, help_text='True для встроенных шаблонов (ЕГЭ/ОГЭ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'тип экзамена',
                'verbose_name_plural': 'типы экзаменов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('icon', models.CharField(blank=True, default='book-open', help_text='Имя иконки из lucide-react', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='knowledge_map.examtype')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['order', 'name'],
                'unique_together': {('exam_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='schedule.group')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='knowledge_map.subject')),
            ],
            options={
                'verbose_name': 'назначение экзамена',
                'verbose_name_plural': 'назначения экзаменов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер задания в экзамене')),
                ('title', models.CharField(help_text='Название темы', max_length=255)),
                ('max_points', models.IntegerField(default=1, help_text='Максимальный балл за задание')),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='knowledge_map.subject')),
            ],
            options={
                'verbose_name': 'тема экзамена',
                'verbose_name_plural': 'темы экзамена',
                'ordering': ['number'],
                'unique_together': {('subject', 'number')},
            },
        ),
        migrations.CreateModel(
            name='StudentTopicScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.FloatField(default=0, help_text='Процент освоения 0-100')),
                ('attempts_count', models.IntegerField(default=0)),
                ('total_points_earned', models.FloatField(default=0)),
                ('total_points_possible', models.FloatField(default=0)),
                ('trend', models.CharField(choices=[('up', 'Растёт'), ('stable', 'Стабильно'), ('down', 'Снижается')], default='stable', max_length=10)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='topic_scores', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='knowledge_map.topic')),
            ],
            options={
                'verbose_name': 'балл ученика по теме',
                'verbose_name_plural': 'баллы учеников по темам',
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
