# Generated by Django 5.2.8 on 2026-02-10 10:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ege', 'ЕГЭ'), ('oge', 'ОГЭ')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Тип экзамена',
                'verbose_name_plural': 'Типы экзаменов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=7)),
                ('max_primary_score', models.PositiveIntegerField(default=0)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='knowledge_map.examtype')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['order', 'name'],
                'unique_together': {('exam_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='knowledge_map.subject')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'code'],
                'unique_together': {('subject', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('task_number', models.PositiveIntegerField(blank=True, help_text='Номер задания в КИМ (1-27 для ЕГЭ мат.профиль и т.д.)', null=True)),
                ('max_score', models.PositiveIntegerField(default=1, help_text='Максимальный балл за задание')),
                ('difficulty', models.CharField(choices=[('base', 'Базовый'), ('medium', 'Повышенный'), ('high', 'Высокий')], default='base', max_length=10)),
                ('fipi_code', models.CharField(blank=True, default='', help_text='Код из кодификатора ФИПИ', max_length=50)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Ключевые слова для поиска/автоматической привязки')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='knowledge_map.section')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order', 'code'],
                'unique_together': {('section', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='knowledge_map.subject')),
            ],
            options={
                'verbose_name': 'Назначение экзамена ученику',
                'verbose_name_plural': 'Назначения экзаменов ученикам',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentTopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0, help_text='Уровень освоения (0-100), взвешенный по давности', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stability', models.FloatField(default=0, help_text='Стабильность результатов (100 = всегда одинаково хорошо)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trend', models.CharField(choices=[('rising', 'Растёт'), ('stable', 'Стабильно'), ('falling', 'Падает'), ('new', 'Мало данных')], default='new', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('learning', 'Изучается'), ('practiced', 'Отработано'), ('mastered', 'Освоено'), ('needs_review', 'Требует повторения')], default='not_started', max_length=20)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('total_score_earned', models.FloatField(default=0)),
                ('total_score_possible', models.FloatField(default=0)),
                ('avg_time_seconds', models.PositiveIntegerField(default=0, help_text='Среднее время на задание (сек)')),
                ('last_scores', models.JSONField(blank=True, default=list, help_text='Последние 10 результатов: [{score, max_score, date, homework_id}]')),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mastery', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mastery', to='knowledge_map.topic')),
            ],
            options={
                'verbose_name': 'Прогресс по теме',
                'verbose_name_plural': 'Прогресс по темам',
                'indexes': [models.Index(fields=['student', 'topic'], name='knowledge_m_student_09eb94_idx'), models.Index(fields=['student', 'mastery_level'], name='knowledge_m_student_018aaa_idx')],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
