# Generated by Django 4.2.26 on 2026-03-08 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0035_group_invite_code_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Magic-link токен для доступа без авторизации', unique=True)),
                ('parent_name', models.CharField(blank=True, default='', help_text='Имя родителя (опционально)', max_length=200)),
                ('parent_contact', models.CharField(blank=True, default='', help_text='Контакт родителя: телефон, telegram и т.д.', max_length=200)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Chat ID для Telegram-уведомлений родителю', max_length=50, null=True)),
                ('telegram_connected', models.BooleanField(default=False)),
                ('alert_missed_hw', models.BooleanField(default=True, help_text='Алерт: ДЗ не сдано более 3 дней после дедлайна')),
                ('alert_missed_lesson', models.BooleanField(default=True, help_text='Алерт: ученик пропустил урок')),
                ('alert_low_balance', models.BooleanField(default=True, help_text='Алерт: баланс уроков <= 2 (будущее)')),
                ('alert_new_grade', models.BooleanField(default=False, help_text='Алерт: новая оценка за контрольную')),
                ('is_active', models.BooleanField(default=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'доступ для родителя',
                'verbose_name_plural': 'доступы для родителей',
            },
        ),
        migrations.CreateModel(
            name='ParentAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_label', models.CharField(help_text='Название предмета для родительского дашборда (задаёт учитель)', max_length=200)),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_homework', models.BooleanField(default=True)),
                ('show_grades', models.BooleanField(default=True)),
                ('show_knowledge_map', models.BooleanField(default=True)),
                ('show_finance', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='Группа, по которой учитель открывает данные', on_delete=django.db.models.deletion.CASCADE, to='schedule.group')),
                ('parent_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='parents.parentaccess')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'грант доступа учителя',
                'verbose_name_plural': 'гранты доступа учителей',
                'unique_together': {('parent_access', 'teacher', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ParentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст комментария для родителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='parents.parentaccessgrant')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комментарий для родителя',
                'verbose_name_plural': 'комментарии для родителей',
                'ordering': ['-created_at'],
            },
        ),
    ]
