# Generated by Django 4.2.26 on 2025-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='teacher_feedback',
            field=models.TextField(blank=True, help_text='Комментарий учителя'),
        ),
        migrations.AddField(
            model_name='answer',
            name='teacher_score',
            field=models.IntegerField(blank=True, help_text='Оценка учителя (переопределяет auto_score)', null=True),
        ),
    ]
