# Generated by Django 4.2.26 on 2025-11-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_answer_teacher_feedback_answer_teacher_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentsubmission',
            index=models.Index(fields=['homework', 'status'], name='hw_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubmission',
            index=models.Index(fields=['student', 'status'], name='student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubmission',
            index=models.Index(fields=['created_at'], name='submission_created_idx'),
        ),
    ]
