# Generated by Django 5.2.11 on 2026-02-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_studentsubmission_hw_status_idx_and_more'),
        ('tenants', '0004_school_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='tenants.tenant', verbose_name='Тенант'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='tenants.tenant', verbose_name='Тенант'),
        ),
    ]
