# Generated by Django 4.2.26 on 2025-12-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_studentsubmission_hw_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архивировано')], default='draft', max_length=20),
        ),
    ]
