# Generated by Django 4.2.26 on 2025-12-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_question_config_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='teacher_feedback_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Общий комментарий учителя к работе: {"text": "...", "attachments": [...]}'),
        ),
    ]
