# Generated by Django 5.2.8 on 2025-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_update_submission_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='ai_grading_enabled',
            field=models.BooleanField(default=False, help_text='Включить AI проверку текстовых ответов'),
        ),
        migrations.AddField(
            model_name='homework',
            name='ai_grading_prompt',
            field=models.TextField(blank=True, help_text='Дополнительные инструкции для AI при проверке (контекст темы, критерии оценки)'),
        ),
        migrations.AddField(
            model_name='homework',
            name='ai_provider',
            field=models.CharField(choices=[('none', 'Без AI'), ('deepseek', 'DeepSeek'), ('openai', 'OpenAI')], default='deepseek', help_text='Провайдер AI для проверки', max_length=20),
        ),
    ]
