# Generated by Django 5.2.8 on 2025-12-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_add_ai_grading_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Крайний срок сдачи', null=True),
        ),
    ]
