# Generated by Django 4.2.26 on 2026-01-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_add_analytics_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
