# Generated by Django 4.2.26 on 2026-01-14 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0025_add_allowed_students_to_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0011_allow_blank_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, которым назначено ДЗ (без привязки к уроку)', related_name='homeworks', to='schedule.group'),
        ),
        migrations.AddField(
            model_name='homework',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Индивидуально назначенные ученики (показывать даже без группы)', limit_choices_to={'role': 'student'}, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homework',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, default='', help_text='ID папки Google Drive, где лежат материалы ДЗ/шаблона', max_length=255),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Если true — это шаблон (архив) для переиспользования'),
        ),
        migrations.AddField(
            model_name='homework',
            name='max_score',
            field=models.IntegerField(default=100, help_text='Максимальный балл (UI/контрольная сумма)'),
        ),
    ]
