# Generated by Django 4.2.26 on 2026-01-17 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_group_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0012_homework_assigned_groups_homework_assigned_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Текстовый ответ'), ('SINGLE_CHOICE', 'Один вариант'), ('MULTI_CHOICE', 'Несколько вариантов'), ('LISTENING', 'Лисенинг'), ('MATCHING', 'Сопоставление'), ('DRAG_DROP', 'Перетаскивание'), ('FILL_BLANKS', 'Заполнение пропусков'), ('HOTSPOT', 'Хотспот на изображении'), ('CODE', 'Программирование')], max_length=20),
        ),
        migrations.CreateModel(
            name='HomeworkGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(blank=True, help_text='Персональный дедлайн для этой группы (если отличается от общего)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='schedule.group')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='homework.homework')),
                ('students', models.ManyToManyField(blank=True, help_text='Конкретные ученики в группе (если пусто - все ученики)', limit_choices_to={'role': 'student'}, related_name='homework_group_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'назначение ДЗ группе',
                'verbose_name_plural': 'назначения ДЗ группам',
                'ordering': ['-created_at'],
                'unique_together': {('homework', 'group')},
            },
        ),
    ]
