# Generated by Django 5.2.8 on 2026-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0013_add_homework_group_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='allow_view_answers',
            field=models.BooleanField(default=True, help_text='Разрешить ученику просматривать свои ответы после сдачи (для КР лучше отключить)'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student_instructions',
            field=models.TextField(blank=True, default='', help_text='Пояснение/инструкции для ученика (показывается перед началом выполнения)'),
        ),
    ]
