# Generated by Django 4.2.26 on 2026-01-17 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0014_add_student_instructions_and_view_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('storage', models.CharField(choices=[('local', 'Локально'), ('gdrive', 'Google Drive')], default='local', max_length=10)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('gdrive_file_id', models.CharField(blank=True, max_length=100)),
                ('gdrive_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('migrated_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'файл домашки',
                'verbose_name_plural': 'файлы домашек',
                'ordering': ['-created_at'],
            },
        ),
    ]
