# Generated by Django 4.2.26 on 2026-01-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_add_homeworkfile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Пояснение для ученика (показывается под вопросом перед ответом)'),
        ),
    ]
