# Generated by Django 5.2 on 2026-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_add_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Список прикреплённых файлов [{url, file_id, name, size, mime_type}]'),
        ),
    ]
