# Generated by Django 4.2.26 on 2026-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0017_add_answer_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_pasted',
            field=models.BooleanField(default=False, help_text='Был ли текст вставлен из буфера обмена'),
        ),
        migrations.AddField(
            model_name='answer',
            name='tab_switches',
            field=models.IntegerField(default=0, help_text='Количество переключений вкладок во время ответа'),
        ),
    ]
