# Generated by Django 4.2.26 on 2026-03-02 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0018_add_telemetry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='revision_comment',
            field=models.TextField(blank=True, default='', help_text='Комментарий учителя при отправке на доработку'),
        ),
        migrations.AddField(
            model_name='homework',
            name='revision_for_student',
            field=models.ForeignKey(blank=True, help_text='Ученик, для которого создана доработка', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_homeworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homework',
            name='revision_of',
            field=models.ForeignKey(blank=True, help_text='Оригинальное ДЗ, из которого создана доработка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='homework.homework'),
        ),
    ]
