# Generated by Django 5.2.8 on 2026-02-08 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0018_add_telemetry_fields'),
        ('tenants', '0002_create_default_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа, которой принадлежит ДЗ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='tenants.school'),
        ),
    ]
