# Generated by Django 5.2.8 on 2026-02-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0019_add_school_fk_to_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Текстовый ответ'), ('SINGLE_CHOICE', 'Один вариант'), ('MULTI_CHOICE', 'Несколько вариантов'), ('LISTENING', 'Лисенинг'), ('MATCHING', 'Сопоставление'), ('DRAG_DROP', 'Перетаскивание'), ('FILL_BLANKS', 'Заполнение пропусков'), ('HOTSPOT', 'Хотспот на изображении'), ('CODE', 'Программирование'), ('FILE_UPLOAD', 'Загрузка файла')], max_length=20),
        ),
    ]
