# Generated by Django 4.2.26 on 2026-03-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0019_add_revision_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfile',
            name='size',
            field=models.BigIntegerField(help_text='Размер файла в байтах'),
        ),
    ]
