# Generated by Django 5.2.8 on 2026-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0020_add_file_upload_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='needs_revision',
            field=models.BooleanField(default=False, help_text='Отмечен учителем для доработки (балл < макс)'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='revision_comment',
            field=models.TextField(blank=True, default='', help_text='Комментарий учителя при отправке на доработку'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='revision_count',
            field=models.IntegerField(default=0, help_text='Сколько раз работа отправлялась на доработку'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('graded', 'Проверено'), ('revision', 'На доработке')], default='in_progress', max_length=20),
        ),
    ]
