# Generated by Django 5.2.8 on 2026-02-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0021_add_revision_fields'),
        ('knowledge_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='exam_topics',
            field=models.ManyToManyField(blank=True, help_text='Темы экзамена, к которым относится ДЗ', related_name='homeworks', to='knowledge_map.topic'),
        ),
    ]
