# Generated by Django 5.2.11 on 2026-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homework_tenant_studentsubmission_tenant'),
        ('homework', '0022_homework_exam_topics'),
    ]

    operations = [
    ]
