# Generated by Django 5.2 on 2026-03-02 11:15
# Increases HomeworkFile.size from IntegerField to BigIntegerField for 2GB+ files

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0026_add_homework_revision_fk_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfile',
            name='size',
            field=models.BigIntegerField(help_text='Размер файла в байтах'),
        ),
    ]
