# Generated by Django 5.2.8 on 2026-03-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0027_increase_file_size_field'),
        ('knowledge_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Тема экзамена для карты знаний (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='knowledge_map.topic'),
        ),
    ]
