# Generated by Django 5.2.8 on 2026-03-04 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0027_increase_file_size_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Человекопонятное имя ключа (gemini-1, gemini-2...)', max_length=100)),
                ('api_key', models.CharField(help_text='API key от AI Studio', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Ключ включён и может использоваться')),
                ('priority', models.IntegerField(default=0, help_text='Приоритет (выше = чаще; для платных ключей)')),
                ('daily_request_limit', models.IntegerField(default=1500, help_text='Макс запросов/день')),
                ('daily_token_limit', models.IntegerField(default=1000000, help_text='Макс токенов/день')),
                ('requests_used_today', models.IntegerField(default=0)),
                ('tokens_used_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, help_text='Дата последнего сброса', null=True)),
                ('consecutive_errors', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('disabled_until', models.DateTimeField(blank=True, help_text='Временно отключён до этого момента', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gemini API ключ',
                'verbose_name_plural': 'Gemini API ключи',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='ai_confidence_threshold',
            field=models.FloatField(default=0.7, help_text='Порог уверенности AI (0.0-1.0). Ниже — работа на ручную проверку'),
        ),
        migrations.AddField(
            model_name='homework',
            name='ai_grading_mode',
            field=models.CharField(choices=[('none', 'Без AI проверки'), ('auto_send', 'AI проверяет и отправляет ученику'), ('teacher_review', 'AI проверяет, учитель подтверждает')], default='none', help_text='Режим AI-проверки: none/auto_send/teacher_review', max_length=20),
        ),
        migrations.CreateModel(
            name='AIGradingUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первое число месяца')),
                ('tokens_used', models.BigIntegerField(default=0)),
                ('requests_count', models.IntegerField(default=0)),
                ('submissions_graded', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grading_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'расход AI по учителю',
                'verbose_name_plural': 'расход AI по учителям',
                'ordering': ['-month'],
                'unique_together': {('teacher', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AIGradingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('manual_review', 'Ручная проверка')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('auto_send', 'AI + отправка ученику'), ('teacher_review', 'AI + ревью учителем')], max_length=20)),
                ('tokens_input', models.IntegerField(default=0, help_text='Входные токены запроса')),
                ('tokens_output', models.IntegerField(default=0, help_text='Выходные токены ответа')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Полный ответ AI')),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grading_jobs', to='homework.homework')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grading_jobs', to='homework.studentsubmission')),
                ('teacher', models.ForeignKey(help_text='Учитель-владелец ДЗ (для учёта лимитов)', on_delete=django.db.models.deletion.CASCADE, related_name='ai_grading_jobs', to=settings.AUTH_USER_MODEL)),
                ('api_key_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='homework.geminiapikey')),
            ],
            options={
                'verbose_name': 'задача AI-проверки',
                'verbose_name_plural': 'задачи AI-проверки',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_job_queue_idx'), models.Index(fields=['teacher', 'created_at'], name='ai_job_teacher_idx')],
            },
        ),
    ]
