# Generated by Django 4.2.26 on 2026-01-27 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0017_add_answer_attachments'),
        ('schedule', '0030_add_ended_at_to_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('lesson_reminder', 'Напоминание об уроке'), ('hw_reminder', 'Напоминание о ДЗ'), ('hw_deadline', 'Напоминание о дедлайне'), ('lesson_cancel', 'Отмена урока'), ('lesson_reschedule', 'Перенос урока'), ('custom', 'Произвольное сообщение')], default='custom', max_length=50, verbose_name='Тип сообщения')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('partially_sent', 'Частично отправлено'), ('cancelled', 'Отменено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to='homework.homework', verbose_name='Домашнее задание')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to='schedule.lesson', verbose_name='Урок')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='scheduled_messages', to='schedule.group', verbose_name='Группы')),
                ('target_students', models.ManyToManyField(blank=True, related_name='received_scheduled_messages', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Запланированное сообщение',
                'verbose_name_plural': 'Запланированные сообщения',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('content', models.TextField(help_text='Плейсхолдеры: {student_name}, {group}, {lesson_title}, {lesson_time}, {hw_title}, {deadline}, {zoom_link}', verbose_name='Текст шаблона')),
                ('message_type', models.CharField(choices=[('lesson_reminder', 'Напоминание об уроке'), ('hw_reminder', 'Напоминание о ДЗ'), ('hw_deadline', 'Напоминание о дедлайне'), ('lesson_cancel', 'Отмена урока'), ('custom', 'Произвольный')], default='custom', max_length=50, verbose_name='Тип шаблона')),
                ('is_system', models.BooleanField(default=False, help_text='Системные шаблоны доступны всем', verbose_name='Системный шаблон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('teacher', models.ForeignKey(blank=True, help_text='Если пусто - системный шаблон', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['-is_system', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_key', models.CharField(help_text='Формат: YYYY-MM-DD-HH', max_length=20, verbose_name='Ключ часа')),
                ('day_key', models.CharField(help_text='Формат: YYYY-MM-DD', max_length=12, verbose_name='Ключ дня')),
                ('hourly_count', models.PositiveIntegerField(default=0, verbose_name='Рассылок за час')),
                ('daily_count', models.PositiveIntegerField(default=0, verbose_name='Рассылок за день')),
                ('last_broadcast_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя рассылка')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_rate_limits', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Лимит рассылок',
                'verbose_name_plural': 'Лимиты рассылок',
            },
        ),
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50, verbose_name='Тип сообщения')),
                ('content_preview', models.CharField(max_length=200, verbose_name='Превью сообщения')),
                ('target_count', models.PositiveIntegerField(default=0, verbose_name='Целевых получателей')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('scheduled_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='bot.scheduledmessage', verbose_name='Запланированное сообщение')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_logs', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['status', 'scheduled_at'], name='bot_schedul_status_548afa_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['teacher', 'status'], name='bot_schedul_teacher_23f3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastratelimit',
            index=models.Index(fields=['teacher', 'day_key'], name='bot_broadca_teacher_64ade1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastratelimit',
            unique_together={('teacher', 'hour_key')},
        ),
        migrations.AddIndex(
            model_name='broadcastlog',
            index=models.Index(fields=['teacher', 'started_at'], name='bot_broadca_teacher_6e0d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastlog',
            index=models.Index(fields=['message_type', 'started_at'], name='bot_broadca_message_5a6b00_idx'),
        ),
    ]
